/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author reyna
 */
public class AdminPostre extends javax.swing.JFrame {
    Connection con = null; 
    Statement stnt = null;


    /**
     * Creates new form AdminPostre
     */
    public AdminPostre() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        
                    try {
    String url = "jdbc:mysql://localhost:3306/restaurante"; // direccion donde se encuentra la base de datos
    String usuario = "root"; // usuario de la gestion de base de datos
    String contraseña = "123"; // contraseña para entrar a la base de datos
                
    Class.forName("com.mysql.jdbc.Driver").newInstance(); // carga el driver para conectarce
    con = (Connection) DriverManager.getConnection(url,usuario,contraseña); // se conecta a la base de datos nuestro programa 
    if(con != null){
                System.out.println("Conexion Exitosa!");
            }else{
                System.out.println("Conexion Fallida!");                
            }
    }catch(Exception e){// excepciones en el caso de haber un error
         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null,e); 
    }
                    
    try {
    stnt = con.createStatement(); 
    ResultSet rsl;
       
    rsl = stnt.executeQuery("SELECT * FROM producto WHERE id>16");
    if(rsl.next()){ 
    postre1.setText(rsl.getString("nombre"));
    subPostre1.setText(rsl.getString("subNombre"));
    precioPostre1.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    postre2.setText(rsl.getString("nombre"));
    subPostre2.setText(rsl.getString("subNombre"));
    precioPostre2.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    postre3.setText(rsl.getString("nombre"));
    subPostre3.setText(rsl.getString("subNombre"));
    precioPostre3.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    postre4.setText(rsl.getString("nombre"));
    subPostre4.setText(rsl.getString("subNombre"));
    precioPostre4.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    postre5.setText(rsl.getString("nombre"));
    subPostre5.setText(rsl.getString("subNombre"));
    precioPostre5.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    postre6.setText(rsl.getString("nombre"));
    subPostre6.setText(rsl.getString("subNombre"));
    precioPostre6.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    postre7.setText(rsl.getString("nombre"));
    subPostre7.setText(rsl.getString("subNombre"));
    precioPostre7.setText(String.valueOf(rsl.getInt("precio")));
    }
    }   catch (SQLException ex) {
            Logger.getLogger(AdminComida.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
     if(cantidad1.getText().equals("")){
            cantidad1.setText("0");
            }if(cantidad2.getText().equals("")){
            cantidad2.setText("0");
            }if(cantidad3.getText().equals("")){
            cantidad3.setText("0");
            }if(cantidad4.getText().equals("")){
            cantidad4.setText("0");
            }if(cantidad5.getText().equals("")){
            cantidad5.setText("0");
            }if(cantidad6.getText().equals("")){
            cantidad6.setText("0");
            }if(cantidad7.getText().equals("")){
            cantidad7.setText("0");
            }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cant13 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        subPostre7 = new javax.swing.JTextArea();
        subPostre6 = new javax.swing.JTextArea();
        subPostre5 = new javax.swing.JTextArea();
        subPostre4 = new javax.swing.JTextArea();
        subPostre3 = new javax.swing.JTextArea();
        subPostre2 = new javax.swing.JTextArea();
        subPostre1 = new javax.swing.JTextArea();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        simbolo1 = new javax.swing.JLabel();
        simbolo2 = new javax.swing.JLabel();
        simbolo3 = new javax.swing.JLabel();
        simbolo4 = new javax.swing.JLabel();
        simbolo5 = new javax.swing.JLabel();
        simbolo6 = new javax.swing.JLabel();
        simbolo7 = new javax.swing.JLabel();
        simbolo8 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cantidad1 = new javax.swing.JTextField();
        cantidad2 = new javax.swing.JTextField();
        cantidad3 = new javax.swing.JTextField();
        cantidad4 = new javax.swing.JTextField();
        cantidad5 = new javax.swing.JTextField();
        cantidad6 = new javax.swing.JTextField();
        cantidad7 = new javax.swing.JTextField();
        postre1 = new javax.swing.JTextArea();
        postre2 = new javax.swing.JTextArea();
        postre3 = new javax.swing.JTextArea();
        postre4 = new javax.swing.JTextArea();
        postre5 = new javax.swing.JTextArea();
        postre6 = new javax.swing.JTextArea();
        postre7 = new javax.swing.JTextArea();
        precioPostre7 = new javax.swing.JTextArea();
        precioPostre6 = new javax.swing.JTextArea();
        precioPostre5 = new javax.swing.JTextArea();
        precioPostre4 = new javax.swing.JTextArea();
        precioPostre3 = new javax.swing.JTextArea();
        precioPostre2 = new javax.swing.JTextArea();
        precioPostre1 = new javax.swing.JTextArea();
        cant8 = new javax.swing.JLabel();
        cant9 = new javax.swing.JLabel();
        cant10 = new javax.swing.JLabel();
        cant11 = new javax.swing.JLabel();
        cant1 = new javax.swing.JLabel();
        cant2 = new javax.swing.JLabel();
        cant12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 940));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 66, 73));
        jLabel4.setText("5.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 530, 60, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen5.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 40, 130, 90);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 66, 73));
        jLabel11.setText("1.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 150, 50, 60);

        cant13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cant13.setForeground(new java.awt.Color(34, 66, 73));
        cant13.setText("Agregar al inventario");
        getContentPane().add(cant13);
        cant13.setBounds(510, 130, 150, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 66, 73));
        jLabel13.setText("2.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 240, 50, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(34, 66, 73));
        jLabel14.setText("3.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 340, 60, 60);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(34, 66, 73));
        jLabel12.setText("VOLVER");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 860, 110, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(34, 66, 73));
        jLabel15.setText("4.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 430, 50, 60);

        subPostre7.setEditable(false);
        subPostre7.setColumns(20);
        subPostre7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre7.setForeground(new java.awt.Color(34, 66, 73));
        subPostre7.setLineWrap(true);
        subPostre7.setRows(5);
        subPostre7.setText("Limon granizado, ron de caña y menta.");
        subPostre7.setBorder(null);
        subPostre7.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre7.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre7.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre7);
        subPostre7.setBounds(60, 760, 300, 80);

        subPostre6.setEditable(false);
        subPostre6.setColumns(20);
        subPostre6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre6.setForeground(new java.awt.Color(34, 66, 73));
        subPostre6.setLineWrap(true);
        subPostre6.setRows(5);
        subPostre6.setText("Helado de frambuesa, limon y frutilla \nsumergidas en frutas en almibar y nata.");
        subPostre6.setBorder(null);
        subPostre6.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre6.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre6.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre6);
        subPostre6.setBounds(60, 660, 300, 70);

        subPostre5.setEditable(false);
        subPostre5.setColumns(20);
        subPostre5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre5.setForeground(new java.awt.Color(34, 66, 73));
        subPostre5.setLineWrap(true);
        subPostre5.setRows(5);
        subPostre5.setText("Helado de fresa,chocolate, vainilla con nata montada en platanos naturales.");
        subPostre5.setBorder(null);
        subPostre5.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre5.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre5.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre5);
        subPostre5.setBounds(60, 570, 300, 60);

        subPostre4.setEditable(false);
        subPostre4.setColumns(20);
        subPostre4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre4.setForeground(new java.awt.Color(34, 66, 73));
        subPostre4.setLineWrap(true);
        subPostre4.setRows(5);
        subPostre4.setText("Esponjoso bizcocho de pistacho cubierto con\ncrema de chocolate blanco.");
        subPostre4.setBorder(null);
        subPostre4.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre4.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre4.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre4);
        subPostre4.setBounds(60, 470, 310, 70);

        subPostre3.setEditable(false);
        subPostre3.setColumns(20);
        subPostre3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre3.setForeground(new java.awt.Color(34, 66, 73));
        subPostre3.setLineWrap(true);
        subPostre3.setRows(5);
        subPostre3.setText("Waffles belgas con frutilla, mora y frambuesa decorados con crema batida y granillos de     chocolate.");
        subPostre3.setBorder(null);
        subPostre3.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre3.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre3.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre3);
        subPostre3.setBounds(60, 380, 310, 60);

        subPostre2.setEditable(false);
        subPostre2.setColumns(20);
        subPostre2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre2.setForeground(new java.awt.Color(34, 66, 73));
        subPostre2.setLineWrap(true);
        subPostre2.setRows(5);
        subPostre2.setText("Una base de biscuit, hojuelas crujientes y un mousse de chocolate amargo.");
        subPostre2.setBorder(null);
        subPostre2.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre2.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre2.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre2);
        subPostre2.setBounds(60, 280, 300, 70);

        subPostre1.setEditable(false);
        subPostre1.setColumns(20);
        subPostre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre1.setForeground(new java.awt.Color(34, 66, 73));
        subPostre1.setLineWrap(true);
        subPostre1.setRows(5);
        subPostre1.setText("Bizcocho de chocolate almendrado con \nmousse de chocolate sobre un espejo de\nBailey´s.");
        subPostre1.setBorder(null);
        subPostre1.setCaretColor(new java.awt.Color(255, 255, 255));
        subPostre1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre1.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre1.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre1);
        subPostre1.setBounds(60, 190, 320, 60);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(34, 66, 73));
        jLabel60.setText("6.");
        getContentPane().add(jLabel60);
        jLabel60.setBounds(30, 620, 50, 60);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(34, 66, 73));
        jLabel61.setText("7.");
        getContentPane().add(jLabel61);
        jLabel61.setBounds(30, 720, 50, 60);

        total2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total2.setForeground(new java.awt.Color(34, 66, 73));
        total2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/agregar.png"))); // NOI18N
        total2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total2MouseClicked(evt);
            }
        });
        getContentPane().add(total2);
        total2.setBounds(400, 840, 200, 80);

        simbolo1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo1.setForeground(new java.awt.Color(255, 102, 0));
        simbolo1.setText("$");
        getContentPane().add(simbolo1);
        simbolo1.setBounds(420, 250, 20, 40);

        simbolo2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo2.setForeground(new java.awt.Color(255, 102, 0));
        simbolo2.setText("$");
        getContentPane().add(simbolo2);
        simbolo2.setBounds(420, 350, 20, 40);

        simbolo3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo3.setForeground(new java.awt.Color(255, 102, 0));
        simbolo3.setText("$");
        getContentPane().add(simbolo3);
        simbolo3.setBounds(420, 440, 20, 40);

        simbolo4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo4.setForeground(new java.awt.Color(255, 102, 0));
        simbolo4.setText("$");
        getContentPane().add(simbolo4);
        simbolo4.setBounds(420, 540, 20, 40);

        simbolo5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo5.setForeground(new java.awt.Color(255, 102, 0));
        simbolo5.setText("$");
        getContentPane().add(simbolo5);
        simbolo5.setBounds(420, 630, 20, 40);

        simbolo6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo6.setForeground(new java.awt.Color(255, 102, 0));
        simbolo6.setText("$");
        getContentPane().add(simbolo6);
        simbolo6.setBounds(420, 730, 20, 40);

        simbolo7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo7.setForeground(new java.awt.Color(255, 102, 0));
        simbolo7.setText("$");
        getContentPane().add(simbolo7);
        simbolo7.setBounds(420, 160, 20, 40);

        simbolo8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo8.setForeground(new java.awt.Color(255, 102, 0));
        simbolo8.setText("$");
        getContentPane().add(simbolo8);
        simbolo8.setBounds(420, 160, 20, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("POSTRES");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 60, 230, 60);

        cantidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad1FocusLost(evt);
            }
        });
        cantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad1);
        cantidad1.setBounds(570, 170, 60, 30);

        cantidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad2FocusLost(evt);
            }
        });
        cantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad2ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad2);
        cantidad2.setBounds(570, 260, 60, 30);

        cantidad3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad3FocusLost(evt);
            }
        });
        cantidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad3ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad3);
        cantidad3.setBounds(570, 360, 60, 30);

        cantidad4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad4FocusLost(evt);
            }
        });
        cantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad4ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad4);
        cantidad4.setBounds(570, 450, 60, 30);

        cantidad5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad5FocusLost(evt);
            }
        });
        cantidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad5ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad5);
        cantidad5.setBounds(570, 550, 60, 30);

        cantidad6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad6FocusLost(evt);
            }
        });
        cantidad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad6ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad6);
        cantidad6.setBounds(570, 640, 60, 30);

        cantidad7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad7FocusLost(evt);
            }
        });
        cantidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad7ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad7);
        cantidad7.setBounds(570, 740, 60, 30);

        postre1.setColumns(20);
        postre1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        postre1.setForeground(new java.awt.Color(255, 102, 0));
        postre1.setLineWrap(true);
        postre1.setRows(5);
        postre1.setText("MOUSSE DE CHOCOLATE");
        postre1.setBorder(null);
        postre1.setCaretColor(new java.awt.Color(255, 255, 255));
        postre1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        postre1.setMinimumSize(new java.awt.Dimension(150, 20));
        postre1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(postre1);
        postre1.setBounds(60, 160, 340, 30);

        postre2.setColumns(20);
        postre2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        postre2.setForeground(new java.awt.Color(255, 102, 0));
        postre2.setLineWrap(true);
        postre2.setRows(5);
        postre2.setText("PASTEL OPERA");
        postre2.setBorder(null);
        postre2.setCaretColor(new java.awt.Color(255, 255, 255));
        postre2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        postre2.setMinimumSize(new java.awt.Dimension(150, 20));
        postre2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(postre2);
        postre2.setBounds(60, 250, 340, 30);

        postre3.setColumns(20);
        postre3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        postre3.setForeground(new java.awt.Color(255, 102, 0));
        postre3.setLineWrap(true);
        postre3.setRows(5);
        postre3.setText("WAFFLES CON FRUTOS ROJOS");
        postre3.setBorder(null);
        postre3.setCaretColor(new java.awt.Color(255, 255, 255));
        postre3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        postre3.setMinimumSize(new java.awt.Dimension(150, 20));
        postre3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(postre3);
        postre3.setBounds(60, 350, 340, 30);

        postre4.setColumns(20);
        postre4.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        postre4.setForeground(new java.awt.Color(255, 102, 0));
        postre4.setLineWrap(true);
        postre4.setRows(5);
        postre4.setText("BIZCOCHO DE PISTACHO");
        postre4.setBorder(null);
        postre4.setCaretColor(new java.awt.Color(255, 255, 255));
        postre4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        postre4.setMinimumSize(new java.awt.Dimension(150, 20));
        postre4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(postre4);
        postre4.setBounds(60, 440, 340, 30);

        postre5.setColumns(20);
        postre5.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        postre5.setForeground(new java.awt.Color(255, 102, 0));
        postre5.setLineWrap(true);
        postre5.setRows(5);
        postre5.setText("BANANA SPLIT");
        postre5.setBorder(null);
        postre5.setCaretColor(new java.awt.Color(255, 255, 255));
        postre5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        postre5.setMinimumSize(new java.awt.Dimension(150, 20));
        postre5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(postre5);
        postre5.setBounds(60, 540, 340, 30);

        postre6.setColumns(20);
        postre6.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        postre6.setForeground(new java.awt.Color(255, 102, 0));
        postre6.setLineWrap(true);
        postre6.setRows(5);
        postre6.setText("POLLO A LA BRASA");
        postre6.setBorder(null);
        postre6.setCaretColor(new java.awt.Color(255, 255, 255));
        postre6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        postre6.setMinimumSize(new java.awt.Dimension(150, 20));
        postre6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(postre6);
        postre6.setBounds(60, 630, 340, 30);

        postre7.setColumns(20);
        postre7.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        postre7.setForeground(new java.awt.Color(255, 102, 0));
        postre7.setLineWrap(true);
        postre7.setRows(5);
        postre7.setText("COPA LIMON Y MENTA");
        postre7.setBorder(null);
        postre7.setCaretColor(new java.awt.Color(255, 255, 255));
        postre7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        postre7.setMinimumSize(new java.awt.Dimension(150, 20));
        postre7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(postre7);
        postre7.setBounds(60, 730, 340, 30);

        precioPostre7.setColumns(20);
        precioPostre7.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioPostre7.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre7.setLineWrap(true);
        precioPostre7.setRows(5);
        precioPostre7.setText("4990\n");
        precioPostre7.setBorder(null);
        precioPostre7.setCaretColor(new java.awt.Color(255, 255, 255));
        precioPostre7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioPostre7.setMinimumSize(new java.awt.Dimension(150, 20));
        precioPostre7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioPostre7);
        precioPostre7.setBounds(440, 740, 70, 30);

        precioPostre6.setColumns(20);
        precioPostre6.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioPostre6.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre6.setLineWrap(true);
        precioPostre6.setRows(5);
        precioPostre6.setText("4990\n");
        precioPostre6.setBorder(null);
        precioPostre6.setCaretColor(new java.awt.Color(255, 255, 255));
        precioPostre6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioPostre6.setMinimumSize(new java.awt.Dimension(150, 20));
        precioPostre6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioPostre6);
        precioPostre6.setBounds(440, 640, 70, 30);

        precioPostre5.setColumns(20);
        precioPostre5.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioPostre5.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre5.setLineWrap(true);
        precioPostre5.setRows(5);
        precioPostre5.setText("4990");
        precioPostre5.setBorder(null);
        precioPostre5.setCaretColor(new java.awt.Color(255, 255, 255));
        precioPostre5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioPostre5.setMinimumSize(new java.awt.Dimension(150, 20));
        precioPostre5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioPostre5);
        precioPostre5.setBounds(440, 550, 70, 30);

        precioPostre4.setColumns(20);
        precioPostre4.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioPostre4.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre4.setLineWrap(true);
        precioPostre4.setRows(5);
        precioPostre4.setText("3990");
        precioPostre4.setBorder(null);
        precioPostre4.setCaretColor(new java.awt.Color(255, 255, 255));
        precioPostre4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioPostre4.setMinimumSize(new java.awt.Dimension(150, 20));
        precioPostre4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioPostre4);
        precioPostre4.setBounds(440, 450, 70, 30);

        precioPostre3.setColumns(20);
        precioPostre3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioPostre3.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre3.setLineWrap(true);
        precioPostre3.setRows(5);
        precioPostre3.setText("3990\n");
        precioPostre3.setBorder(null);
        precioPostre3.setCaretColor(new java.awt.Color(255, 255, 255));
        precioPostre3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioPostre3.setMinimumSize(new java.awt.Dimension(150, 20));
        precioPostre3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioPostre3);
        precioPostre3.setBounds(440, 360, 70, 30);

        precioPostre2.setColumns(20);
        precioPostre2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioPostre2.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre2.setLineWrap(true);
        precioPostre2.setRows(5);
        precioPostre2.setText("3990\n");
        precioPostre2.setBorder(null);
        precioPostre2.setCaretColor(new java.awt.Color(255, 255, 255));
        precioPostre2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioPostre2.setMinimumSize(new java.awt.Dimension(150, 20));
        precioPostre2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioPostre2);
        precioPostre2.setBounds(440, 260, 70, 30);

        precioPostre1.setColumns(20);
        precioPostre1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioPostre1.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre1.setLineWrap(true);
        precioPostre1.setRows(5);
        precioPostre1.setText("3990");
        precioPostre1.setBorder(null);
        precioPostre1.setCaretColor(new java.awt.Color(255, 255, 255));
        precioPostre1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioPostre1.setMinimumSize(new java.awt.Dimension(150, 20));
        precioPostre1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioPostre1);
        precioPostre1.setBounds(440, 170, 70, 30);

        cant8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant8.setForeground(new java.awt.Color(34, 66, 73));
        cant8.setText("Cant.");
        getContentPane().add(cant8);
        cant8.setBounds(510, 350, 70, 40);

        cant9.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant9.setForeground(new java.awt.Color(34, 66, 73));
        cant9.setText("Cant.");
        getContentPane().add(cant9);
        cant9.setBounds(510, 440, 70, 40);

        cant10.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant10.setForeground(new java.awt.Color(34, 66, 73));
        cant10.setText("Cant.");
        getContentPane().add(cant10);
        cant10.setBounds(510, 550, 70, 40);

        cant11.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant11.setForeground(new java.awt.Color(34, 66, 73));
        cant11.setText("Cant.");
        getContentPane().add(cant11);
        cant11.setBounds(510, 740, 70, 40);

        cant1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant1.setForeground(new java.awt.Color(34, 66, 73));
        cant1.setText("Cant.");
        getContentPane().add(cant1);
        cant1.setBounds(510, 160, 70, 40);

        cant2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant2.setForeground(new java.awt.Color(34, 66, 73));
        cant2.setText("Cant.");
        getContentPane().add(cant2);
        cant2.setBounds(510, 250, 70, 40);

        cant12.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant12.setForeground(new java.awt.Color(34, 66, 73));
        cant12.setText("Cant.");
        getContentPane().add(cant12);
        cant12.setBounds(510, 640, 70, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/93b5f9913d2e4316cd6e541c67b9aed0.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 1880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void total2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total2MouseClicked

         try {
            // TODO add your handling code here:
            stnt = con.createStatement();
            
            ResultSet rsl = stnt.executeQuery("SELECT * FROM producto WHERE nombre =  '"+ postre1.getText()+"' AND subNombre = '"+subPostre1.getText()+"' AND precio = "+ precioPostre1.getText()+ "");
            if(!rsl.next()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ postre1.getText()+"', subNombre = '"+subPostre1.getText()+"', precio = "+ precioPostre1.getText()+ " WHERE id = 17");}
            
           
            ResultSet rs2 = stnt.executeQuery("SELECT * FROM producto WHERE nombre =  '"+ postre2.getText()+"' AND subNombre = '"+subPostre2.getText()+"' AND precio = "+ precioPostre2.getText()+ "");
            if(!rs2.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ postre2.getText()+"', subNombre = '"+subPostre2.getText()+"', precio = "+ precioPostre2.getText()+ " WHERE id = 18");               
            }
            
            
            ResultSet rs3 = stnt.executeQuery("SELECT * FROM producto WHERE nombre = '"+ postre3.getText()+"' AND subNombre = '"+subPostre3.getText()+"' AND precio = "+ precioPostre3.getText()+ "");
            if(!rs3.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ postre3.getText()+"', subNombre = '"+subPostre3.getText()+"', precio = "+ precioPostre3.getText()+ " WHERE id = 19");               
            }
            
            
            ResultSet rs4 = stnt.executeQuery("SELECT * FROM producto WHERE nombre ='"+ postre4.getText()+"' AND subNombre = '"+subPostre4.getText()+"' AND precio = "+ precioPostre4.getText()+ "");
            if(!rs4.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ postre4.getText()+"', subNombre = '"+subPostre4.getText()+"', precio = "+ precioPostre4.getText()+ " WHERE id = 20");               
            }
            
            
            ResultSet rs5 = stnt.executeQuery("SELECT * FROM producto WHERE nombre = '"+ postre5.getText()+"' AND subNombre = '"+subPostre5.getText()+"' AND precio = "+ precioPostre5.getText()+ "");
            if(!rs5.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ postre5.getText()+"', subNombre = '"+subPostre5.getText()+"', precio = "+ precioPostre5.getText()+ " WHERE id = 21");               
            }
            
            ResultSet rs6 = stnt.executeQuery("SELECT * FROM producto WHERE nombre = '"+ postre6.getText()+"' AND subNombre = '"+subPostre6.getText()+"' AND precio = "+precioPostre6.getText()+ "");
            if(!rs6.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ postre6.getText()+"', subNombre = '"+subPostre6.getText()+"', precio = "+ precioPostre6.getText()+ " WHERE id = 22");               
            }
            
            ResultSet rs7 = stnt.executeQuery("SELECT * FROM producto WHERE nombre = '"+ postre7.getText()+"' AND subNombre = '"+subPostre7.getText()+"' AND precio = "+ precioPostre7.getText()+ "");
            if(!rs7.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ postre7.getText()+"', subNombre = '"+subPostre7.getText()+"', precio = "+ precioPostre7.getText()+ " WHERE id = 23");               
            }
            
            if(Integer.parseInt(cantidad1.getText())>0){
            ResultSet rsa = stnt.executeQuery("CALL ingresoInventario("+cantidad1.getText()+",17)");
            }
            if(Integer.parseInt(cantidad2.getText())>0){
            ResultSet rsb = stnt.executeQuery("CALL ingresoInventario("+cantidad2.getText()+",18)");
            }
            if(Integer.parseInt(cantidad3.getText())>0){
            ResultSet rsc = stnt.executeQuery("CALL ingresoInventario("+cantidad3.getText()+",19)");
            }
           if(Integer.parseInt(cantidad4.getText())>0){
            ResultSet rsd = stnt.executeQuery("CALL ingresoInventario("+cantidad4.getText()+",20)");
            }                       
           if(Integer.parseInt(cantidad5.getText())>0){
            ResultSet rse = stnt.executeQuery("CALL ingresoInventario("+cantidad5.getText()+",21)");
            }            
           if(Integer.parseInt(cantidad6.getText())>0){
            ResultSet rsf = stnt.executeQuery("CALL ingresoInventario("+cantidad6.getText()+",22)");
            }
           if(Integer.parseInt(cantidad7.getText())>0){
            ResultSet rsg = stnt.executeQuery("CALL ingresoInventario("+cantidad7.getText()+",23)");
            } 
 

                 
         }catch (SQLException ex) {        
        }
        AdminMenu go = new AdminMenu();
        go.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_total2MouseClicked

    private void cantidad1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad1FocusGained
        // TODO add your handling code here:
        if(cantidad1.getText().equals("0")){
            cantidad1.setText("");

        }
    }//GEN-LAST:event_cantidad1FocusGained

    private void cantidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad1FocusLost
        // TODO add your handling code here:
        if(cantidad1.getText().equals("")){
            cantidad1.setText("0");
        }
    }//GEN-LAST:event_cantidad1FocusLost

    private void cantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad1ActionPerformed

    private void cantidad3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad3FocusGained
        // TODO add your handling code here:
        if(cantidad3.getText().equals("0")){
            cantidad3.setText("");}
    }//GEN-LAST:event_cantidad3FocusGained

    private void cantidad3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad3FocusLost
        // TODO add your handling code here:
        if(cantidad3.getText().equals("")){
            cantidad3.setText("0");
        }
    }//GEN-LAST:event_cantidad3FocusLost

    private void cantidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad3ActionPerformed

    private void cantidad4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad4FocusGained
        // TODO add your handling code here:
        if(cantidad4.getText().equals("0")){
            cantidad4.setText("");}
    }//GEN-LAST:event_cantidad4FocusGained

    private void cantidad4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad4FocusLost
        // TODO add your handling code here:
        if(cantidad4.getText().equals("")){
            cantidad4.setText("0");
        }
    }//GEN-LAST:event_cantidad4FocusLost

    private void cantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad4ActionPerformed

    private void cantidad5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad5FocusGained
        // TODO add your handling code here:
        if(cantidad5.getText().equals("0")){
            cantidad5.setText("");}
    }//GEN-LAST:event_cantidad5FocusGained

    private void cantidad5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad5FocusLost
        // TODO add your handling code here:
        if(cantidad5.getText().equals("")){
            cantidad5.setText("0");
        }
    }//GEN-LAST:event_cantidad5FocusLost

    private void cantidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad5ActionPerformed

    private void cantidad6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad6FocusGained
        // TODO add your handling code here:
        if(cantidad6.getText().equals("0")){
            cantidad6.setText("");
        }
    }//GEN-LAST:event_cantidad6FocusGained

    private void cantidad6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad6FocusLost
        // TODO add your handling code here:
        if(cantidad6.getText().equals("")){
            cantidad6.setText("0");}
    }//GEN-LAST:event_cantidad6FocusLost

    private void cantidad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad6ActionPerformed

    private void cantidad7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad7FocusGained
        // TODO add your handling code here:
        if(cantidad7.getText().equals("0")){
            cantidad7.setText("");}
    }//GEN-LAST:event_cantidad7FocusGained

    private void cantidad7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad7FocusLost
        // TODO add your handling code here:
        if(cantidad7.getText().equals("")){
            cantidad7.setText("0");
        }
    }//GEN-LAST:event_cantidad7FocusLost

    private void cantidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad7ActionPerformed

    private void cantidad2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad2FocusGained
        // TODO add your handling code here:
        if(cantidad2.getText().equals("0")){
            cantidad2.setText("");}
    }//GEN-LAST:event_cantidad2FocusGained

    private void cantidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad2FocusLost
        // TODO add your handling code here:
        if(cantidad2.getText().equals("")){
            cantidad2.setText("0");
        }
    }//GEN-LAST:event_cantidad2FocusLost

    private void cantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad2ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
            if(cantidad1.getText().equals("")){
            cantidad1.setText("0");
            }if(cantidad2.getText().equals("")){
            cantidad2.setText("0");
            }if(cantidad3.getText().equals("")){
            cantidad3.setText("0");
            }if(cantidad4.getText().equals("")){
            cantidad4.setText("0");
            }if(cantidad5.getText().equals("")){
            cantidad5.setText("0");
            }if(cantidad6.getText().equals("")){
            cantidad6.setText("0");
            }if(cantidad7.getText().equals("")){
            cantidad7.setText("0");}    
  
            
    }//GEN-LAST:event_formMouseMoved

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        AdminMenu go = new AdminMenu();
        go.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPostre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cant1;
    private javax.swing.JLabel cant10;
    private javax.swing.JLabel cant11;
    private javax.swing.JLabel cant12;
    private javax.swing.JLabel cant13;
    private javax.swing.JLabel cant2;
    private javax.swing.JLabel cant8;
    private javax.swing.JLabel cant9;
    private javax.swing.JTextField cantidad1;
    private javax.swing.JTextField cantidad2;
    private javax.swing.JTextField cantidad3;
    private javax.swing.JTextField cantidad4;
    private javax.swing.JTextField cantidad5;
    private javax.swing.JTextField cantidad6;
    private javax.swing.JTextField cantidad7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextArea postre1;
    private javax.swing.JTextArea postre2;
    private javax.swing.JTextArea postre3;
    private javax.swing.JTextArea postre4;
    private javax.swing.JTextArea postre5;
    private javax.swing.JTextArea postre6;
    private javax.swing.JTextArea postre7;
    private javax.swing.JTextArea precioPostre1;
    private javax.swing.JTextArea precioPostre2;
    private javax.swing.JTextArea precioPostre3;
    private javax.swing.JTextArea precioPostre4;
    private javax.swing.JTextArea precioPostre5;
    private javax.swing.JTextArea precioPostre6;
    private javax.swing.JTextArea precioPostre7;
    private javax.swing.JLabel simbolo1;
    private javax.swing.JLabel simbolo2;
    private javax.swing.JLabel simbolo3;
    private javax.swing.JLabel simbolo4;
    private javax.swing.JLabel simbolo5;
    private javax.swing.JLabel simbolo6;
    private javax.swing.JLabel simbolo7;
    private javax.swing.JLabel simbolo8;
    private javax.swing.JTextArea subPostre1;
    private javax.swing.JTextArea subPostre2;
    private javax.swing.JTextArea subPostre3;
    private javax.swing.JTextArea subPostre4;
    private javax.swing.JTextArea subPostre5;
    private javax.swing.JTextArea subPostre6;
    private javax.swing.JTextArea subPostre7;
    private javax.swing.JLabel total2;
    // End of variables declaration//GEN-END:variables
}
