/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

/**
 *
 * @author reyna
 */
public class AdminComida extends javax.swing.JFrame {

    /**
     * Creates new form AdminComida
     */
    public AdminComida() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precioComida1 = new javax.swing.JTextArea();
        precioComida2 = new javax.swing.JTextArea();
        precioComida3 = new javax.swing.JTextArea();
        precioComida4 = new javax.swing.JTextArea();
        precioComida5 = new javax.swing.JTextArea();
        precioComida6 = new javax.swing.JTextArea();
        precioComida7 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comida1 = new javax.swing.JTextArea();
        comida2 = new javax.swing.JTextArea();
        comida3 = new javax.swing.JTextArea();
        comida4 = new javax.swing.JTextArea();
        comida5 = new javax.swing.JTextArea();
        comida6 = new javax.swing.JTextArea();
        comida7 = new javax.swing.JTextArea();
        subComida1 = new javax.swing.JTextArea();
        subComida2 = new javax.swing.JTextArea();
        subComida3 = new javax.swing.JTextArea();
        subComida4 = new javax.swing.JTextArea();
        subComida5 = new javax.swing.JTextArea();
        subComida6 = new javax.swing.JTextArea();
        subComida7 = new javax.swing.JTextArea();
        cantidad1 = new javax.swing.JTextField();
        cantidad3 = new javax.swing.JTextField();
        cantidad4 = new javax.swing.JTextField();
        cantidad5 = new javax.swing.JTextField();
        cantidad6 = new javax.swing.JTextField();
        cantidad7 = new javax.swing.JTextField();
        cantidad2 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        agregar = new javax.swing.JLabel();
        simbolo1 = new javax.swing.JLabel();
        simbolo2 = new javax.swing.JLabel();
        simbolo3 = new javax.swing.JLabel();
        simbolo4 = new javax.swing.JLabel();
        simbolo5 = new javax.swing.JLabel();
        simbolo6 = new javax.swing.JLabel();
        simbolo7 = new javax.swing.JLabel();
        simbolo8 = new javax.swing.JLabel();
        cant1 = new javax.swing.JLabel();
        cant2 = new javax.swing.JLabel();
        cant3 = new javax.swing.JLabel();
        cant4 = new javax.swing.JLabel();
        cant5 = new javax.swing.JLabel();
        cant6 = new javax.swing.JLabel();
        cant7 = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 940));
        setPreferredSize(new java.awt.Dimension(680, 940));
        getContentPane().setLayout(null);

        precioComida1.setColumns(20);
        precioComida1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioComida1.setForeground(new java.awt.Color(255, 102, 0));
        precioComida1.setLineWrap(true);
        precioComida1.setRows(5);
        precioComida1.setText("7990");
        precioComida1.setBorder(null);
        precioComida1.setCaretColor(new java.awt.Color(255, 255, 255));
        precioComida1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioComida1.setMinimumSize(new java.awt.Dimension(150, 20));
        precioComida1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioComida1);
        precioComida1.setBounds(440, 170, 70, 30);

        precioComida2.setColumns(20);
        precioComida2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioComida2.setForeground(new java.awt.Color(255, 102, 0));
        precioComida2.setLineWrap(true);
        precioComida2.setRows(5);
        precioComida2.setText("6990");
        precioComida2.setBorder(null);
        precioComida2.setCaretColor(new java.awt.Color(255, 255, 255));
        precioComida2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioComida2.setMinimumSize(new java.awt.Dimension(150, 20));
        precioComida2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioComida2);
        precioComida2.setBounds(440, 260, 70, 30);

        precioComida3.setColumns(20);
        precioComida3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioComida3.setForeground(new java.awt.Color(255, 102, 0));
        precioComida3.setLineWrap(true);
        precioComida3.setRows(5);
        precioComida3.setText("7990");
        precioComida3.setBorder(null);
        precioComida3.setCaretColor(new java.awt.Color(255, 255, 255));
        precioComida3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioComida3.setMinimumSize(new java.awt.Dimension(150, 20));
        precioComida3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioComida3);
        precioComida3.setBounds(440, 360, 70, 30);

        precioComida4.setColumns(20);
        precioComida4.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioComida4.setForeground(new java.awt.Color(255, 102, 0));
        precioComida4.setLineWrap(true);
        precioComida4.setRows(5);
        precioComida4.setText("9990");
        precioComida4.setBorder(null);
        precioComida4.setCaretColor(new java.awt.Color(255, 255, 255));
        precioComida4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioComida4.setMinimumSize(new java.awt.Dimension(150, 20));
        precioComida4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioComida4);
        precioComida4.setBounds(440, 450, 70, 30);

        precioComida5.setColumns(20);
        precioComida5.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioComida5.setForeground(new java.awt.Color(255, 102, 0));
        precioComida5.setLineWrap(true);
        precioComida5.setRows(5);
        precioComida5.setText("6990");
        precioComida5.setBorder(null);
        precioComida5.setCaretColor(new java.awt.Color(255, 255, 255));
        precioComida5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioComida5.setMinimumSize(new java.awt.Dimension(150, 20));
        precioComida5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioComida5);
        precioComida5.setBounds(440, 550, 70, 30);

        precioComida6.setColumns(20);
        precioComida6.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioComida6.setForeground(new java.awt.Color(255, 102, 0));
        precioComida6.setLineWrap(true);
        precioComida6.setRows(5);
        precioComida6.setText("7990");
        precioComida6.setBorder(null);
        precioComida6.setCaretColor(new java.awt.Color(255, 255, 255));
        precioComida6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioComida6.setMinimumSize(new java.awt.Dimension(150, 20));
        precioComida6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioComida6);
        precioComida6.setBounds(440, 640, 70, 30);

        precioComida7.setColumns(20);
        precioComida7.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioComida7.setForeground(new java.awt.Color(255, 102, 0));
        precioComida7.setLineWrap(true);
        precioComida7.setRows(5);
        precioComida7.setText("8990");
        precioComida7.setBorder(null);
        precioComida7.setCaretColor(new java.awt.Color(255, 255, 255));
        precioComida7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioComida7.setMinimumSize(new java.awt.Dimension(150, 20));
        precioComida7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioComida7);
        precioComida7.setBounds(440, 740, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 66, 73));
        jLabel4.setText("5.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 530, 60, 60);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(34, 66, 73));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen2.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 10, 130, 130);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("COMIDA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 50, 230, 60);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 66, 73));
        jLabel11.setText("1.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 150, 50, 60);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 66, 73));
        jLabel13.setText("2.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 240, 50, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(34, 66, 73));
        jLabel14.setText("3.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 340, 60, 60);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(34, 66, 73));
        jLabel15.setText("4.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 430, 50, 60);

        comida1.setColumns(20);
        comida1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        comida1.setForeground(new java.awt.Color(255, 102, 0));
        comida1.setLineWrap(true);
        comida1.setRows(5);
        comida1.setText("LOMO MANTARO");
        comida1.setBorder(null);
        comida1.setCaretColor(new java.awt.Color(255, 255, 255));
        comida1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        comida1.setMinimumSize(new java.awt.Dimension(150, 20));
        comida1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(comida1);
        comida1.setBounds(60, 160, 340, 30);

        comida2.setColumns(20);
        comida2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        comida2.setForeground(new java.awt.Color(255, 102, 0));
        comida2.setLineWrap(true);
        comida2.setRows(5);
        comida2.setText("LOMO GIUSEPPI VERDI");
        comida2.setBorder(null);
        comida2.setCaretColor(new java.awt.Color(255, 255, 255));
        comida2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        comida2.setMinimumSize(new java.awt.Dimension(150, 20));
        comida2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(comida2);
        comida2.setBounds(60, 250, 340, 30);

        comida3.setColumns(20);
        comida3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        comida3.setForeground(new java.awt.Color(255, 102, 0));
        comida3.setLineWrap(true);
        comida3.setRows(5);
        comida3.setText("BIFE BRAVO");
        comida3.setBorder(null);
        comida3.setCaretColor(new java.awt.Color(255, 255, 255));
        comida3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        comida3.setMinimumSize(new java.awt.Dimension(150, 20));
        comida3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(comida3);
        comida3.setBounds(60, 350, 340, 30);

        comida4.setColumns(20);
        comida4.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        comida4.setForeground(new java.awt.Color(255, 102, 0));
        comida4.setLineWrap(true);
        comida4.setRows(5);
        comida4.setText("BIFE CORLEONE");
        comida4.setBorder(null);
        comida4.setCaretColor(new java.awt.Color(255, 255, 255));
        comida4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        comida4.setMinimumSize(new java.awt.Dimension(150, 20));
        comida4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(comida4);
        comida4.setBounds(60, 440, 340, 30);

        comida5.setColumns(20);
        comida5.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        comida5.setForeground(new java.awt.Color(255, 102, 0));
        comida5.setLineWrap(true);
        comida5.setRows(5);
        comida5.setText("PECHUGA PARRILLERA");
        comida5.setBorder(null);
        comida5.setCaretColor(new java.awt.Color(255, 255, 255));
        comida5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        comida5.setMinimumSize(new java.awt.Dimension(150, 20));
        comida5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(comida5);
        comida5.setBounds(60, 540, 340, 30);

        comida6.setColumns(20);
        comida6.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        comida6.setForeground(new java.awt.Color(255, 102, 0));
        comida6.setLineWrap(true);
        comida6.setRows(5);
        comida6.setText("POLLO A LA BRASA");
        comida6.setBorder(null);
        comida6.setCaretColor(new java.awt.Color(255, 255, 255));
        comida6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        comida6.setMinimumSize(new java.awt.Dimension(150, 20));
        comida6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(comida6);
        comida6.setBounds(60, 630, 340, 30);

        comida7.setColumns(20);
        comida7.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        comida7.setForeground(new java.awt.Color(255, 102, 0));
        comida7.setLineWrap(true);
        comida7.setRows(5);
        comida7.setText("PARRILLA PERSONAL");
        comida7.setBorder(null);
        comida7.setCaretColor(new java.awt.Color(255, 255, 255));
        comida7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        comida7.setMinimumSize(new java.awt.Dimension(150, 20));
        comida7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(comida7);
        comida7.setBounds(60, 730, 340, 30);

        subComida1.setColumns(20);
        subComida1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subComida1.setForeground(new java.awt.Color(34, 66, 73));
        subComida1.setLineWrap(true);
        subComida1.setRows(5);
        subComida1.setText("Una version distinta pero igual de deliciosa \nacompañada con fetuccinnis en salsa hungara.");
        subComida1.setBorder(null);
        subComida1.setCaretColor(new java.awt.Color(255, 255, 255));
        subComida1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subComida1.setMinimumSize(new java.awt.Dimension(150, 20));
        subComida1.setPreferredSize(new java.awt.Dimension(280, 100));
        subComida1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subComida1);
        subComida1.setBounds(60, 190, 310, 70);

        subComida2.setColumns(20);
        subComida2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subComida2.setForeground(new java.awt.Color(34, 66, 73));
        subComida2.setLineWrap(true);
        subComida2.setRows(5);
        subComida2.setText("Lomo acompañado de deliciosos fetuccinnis \nbañados en una clasica salsa italiana. ");
        subComida2.setBorder(null);
        subComida2.setCaretColor(new java.awt.Color(34, 66, 73));
        subComida2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subComida2.setMinimumSize(new java.awt.Dimension(150, 20));
        subComida2.setPreferredSize(new java.awt.Dimension(280, 100));
        subComida2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subComida2);
        subComida2.setBounds(60, 280, 300, 70);

        subComida3.setColumns(20);
        subComida3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subComida3.setForeground(new java.awt.Color(34, 66, 73));
        subComida3.setLineWrap(true);
        subComida3.setRows(5);
        subComida3.setText("Bife ancho de res acompañado de nuestras   inigualables papas bravas.");
        subComida3.setBorder(null);
        subComida3.setCaretColor(new java.awt.Color(34, 66, 73));
        subComida3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subComida3.setMinimumSize(new java.awt.Dimension(150, 20));
        subComida3.setPreferredSize(new java.awt.Dimension(280, 100));
        subComida3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subComida3);
        subComida3.setBounds(60, 380, 300, 60);

        subComida4.setColumns(20);
        subComida4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subComida4.setForeground(new java.awt.Color(34, 66, 73));
        subComida4.setLineWrap(true);
        subComida4.setRows(5);
        subComida4.setText("Bife ancho de res, bañado en nuestra cremosa\nsalsa de pimienta negra y fetuccinnis bañados en mantequilla y salvia.");
        subComida4.setBorder(null);
        subComida4.setCaretColor(new java.awt.Color(34, 66, 73));
        subComida4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subComida4.setMinimumSize(new java.awt.Dimension(150, 20));
        subComida4.setPreferredSize(new java.awt.Dimension(280, 100));
        subComida4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subComida4);
        subComida4.setBounds(60, 470, 310, 70);

        subComida5.setColumns(20);
        subComida5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subComida5.setForeground(new java.awt.Color(34, 66, 73));
        subComida5.setLineWrap(true);
        subComida5.setRows(5);
        subComida5.setText("Pechuga acompañada con arroz y ensalada\nmixta.");
        subComida5.setBorder(null);
        subComida5.setCaretColor(new java.awt.Color(34, 66, 73));
        subComida5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subComida5.setMinimumSize(new java.awt.Dimension(150, 20));
        subComida5.setPreferredSize(new java.awt.Dimension(280, 100));
        subComida5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subComida5);
        subComida5.setBounds(60, 570, 300, 60);

        subComida6.setColumns(20);
        subComida6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subComida6.setForeground(new java.awt.Color(34, 66, 73));
        subComida6.setLineWrap(true);
        subComida6.setRows(5);
        subComida6.setText("1/4 de pollo acompañado con papas fritas.");
        subComida6.setBorder(null);
        subComida6.setCaretColor(new java.awt.Color(34, 66, 73));
        subComida6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subComida6.setMinimumSize(new java.awt.Dimension(150, 20));
        subComida6.setPreferredSize(new java.awt.Dimension(280, 100));
        subComida6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subComida6);
        subComida6.setBounds(60, 660, 300, 70);

        subComida7.setColumns(20);
        subComida7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subComida7.setForeground(new java.awt.Color(34, 66, 73));
        subComida7.setLineWrap(true);
        subComida7.setRows(5);
        subComida7.setText("Nuestra deliciosa parrilla incluye bife ancho de res, pechuga de pollo, carne de cerdo, \nsalchicha farnkfuter y papas fritas.");
        subComida7.setBorder(null);
        subComida7.setCaretColor(new java.awt.Color(34, 66, 73));
        subComida7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subComida7.setMinimumSize(new java.awt.Dimension(150, 20));
        subComida7.setPreferredSize(new java.awt.Dimension(280, 100));
        subComida7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subComida7);
        subComida7.setBounds(60, 760, 300, 100);

        cantidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad1FocusLost(evt);
            }
        });
        cantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad1);
        cantidad1.setBounds(570, 170, 60, 30);

        cantidad3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad3FocusLost(evt);
            }
        });
        cantidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad3ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad3);
        cantidad3.setBounds(570, 360, 60, 30);

        cantidad4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad4FocusLost(evt);
            }
        });
        cantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad4ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad4);
        cantidad4.setBounds(570, 450, 60, 30);

        cantidad5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad5FocusLost(evt);
            }
        });
        cantidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad5ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad5);
        cantidad5.setBounds(570, 550, 60, 30);

        cantidad6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad6FocusLost(evt);
            }
        });
        cantidad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad6ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad6);
        cantidad6.setBounds(570, 640, 60, 30);

        cantidad7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad7FocusLost(evt);
            }
        });
        cantidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad7ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad7);
        cantidad7.setBounds(570, 740, 60, 30);

        cantidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad2FocusLost(evt);
            }
        });
        cantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad2ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad2);
        cantidad2.setBounds(570, 260, 60, 30);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(34, 66, 73));
        jLabel60.setText("6.");
        getContentPane().add(jLabel60);
        jLabel60.setBounds(30, 620, 50, 60);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(34, 66, 73));
        jLabel61.setText("7.");
        getContentPane().add(jLabel61);
        jLabel61.setBounds(30, 720, 50, 60);

        agregar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        agregar.setForeground(new java.awt.Color(34, 66, 73));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/agregar.png"))); // NOI18N
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(420, 840, 200, 80);

        simbolo1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo1.setForeground(new java.awt.Color(255, 102, 0));
        simbolo1.setText("$");
        getContentPane().add(simbolo1);
        simbolo1.setBounds(420, 250, 20, 40);

        simbolo2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo2.setForeground(new java.awt.Color(255, 102, 0));
        simbolo2.setText("$");
        getContentPane().add(simbolo2);
        simbolo2.setBounds(420, 350, 20, 40);

        simbolo3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo3.setForeground(new java.awt.Color(255, 102, 0));
        simbolo3.setText("$");
        getContentPane().add(simbolo3);
        simbolo3.setBounds(420, 440, 20, 40);

        simbolo4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo4.setForeground(new java.awt.Color(255, 102, 0));
        simbolo4.setText("$");
        getContentPane().add(simbolo4);
        simbolo4.setBounds(420, 540, 20, 40);

        simbolo5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo5.setForeground(new java.awt.Color(255, 102, 0));
        simbolo5.setText("$");
        getContentPane().add(simbolo5);
        simbolo5.setBounds(420, 630, 20, 40);

        simbolo6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo6.setForeground(new java.awt.Color(255, 102, 0));
        simbolo6.setText("$");
        getContentPane().add(simbolo6);
        simbolo6.setBounds(420, 730, 20, 40);

        simbolo7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo7.setForeground(new java.awt.Color(255, 102, 0));
        simbolo7.setText("$");
        getContentPane().add(simbolo7);
        simbolo7.setBounds(420, 160, 20, 40);

        simbolo8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo8.setForeground(new java.awt.Color(255, 102, 0));
        simbolo8.setText("$");
        getContentPane().add(simbolo8);
        simbolo8.setBounds(420, 160, 20, 40);

        cant1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant1.setForeground(new java.awt.Color(34, 66, 73));
        cant1.setText("Stock");
        getContentPane().add(cant1);
        cant1.setBounds(510, 160, 70, 40);

        cant2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant2.setForeground(new java.awt.Color(34, 66, 73));
        cant2.setText("Stock");
        getContentPane().add(cant2);
        cant2.setBounds(510, 250, 70, 40);

        cant3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant3.setForeground(new java.awt.Color(34, 66, 73));
        cant3.setText("Stock");
        getContentPane().add(cant3);
        cant3.setBounds(510, 350, 70, 40);

        cant4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant4.setForeground(new java.awt.Color(34, 66, 73));
        cant4.setText("Stock");
        getContentPane().add(cant4);
        cant4.setBounds(510, 440, 70, 40);

        cant5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant5.setForeground(new java.awt.Color(34, 66, 73));
        cant5.setText("Stock");
        getContentPane().add(cant5);
        cant5.setBounds(510, 540, 70, 40);

        cant6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant6.setForeground(new java.awt.Color(34, 66, 73));
        cant6.setText("Stock");
        getContentPane().add(cant6);
        cant6.setBounds(510, 630, 70, 40);

        cant7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant7.setForeground(new java.awt.Color(34, 66, 73));
        cant7.setText("Stock");
        getContentPane().add(cant7);
        cant7.setBounds(510, 730, 70, 40);

        total2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total2.setForeground(new java.awt.Color(34, 66, 73));
        getContentPane().add(total2);
        total2.setBounds(140, 860, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/93b5f9913d2e4316cd6e541c67b9aed0.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 930);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked

        Carta go = new Carta();
        go.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_agregarMouseClicked

    private void cantidad1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad1FocusGained
        // TODO add your handling code here:
        if(cantidad1.getText().equals("0")){
            cantidad1.setText("");

        }
    }//GEN-LAST:event_cantidad1FocusGained

    private void cantidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad1FocusLost
        // TODO add your handling code here:
        if(cantidad1.getText().equals("")){
            cantidad1.setText("0");
        }
    }//GEN-LAST:event_cantidad1FocusLost

    private void cantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad1ActionPerformed

    private void cantidad3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad3FocusGained
        // TODO add your handling code here:
        if(cantidad3.getText().equals("0")){
            cantidad3.setText("");}
    }//GEN-LAST:event_cantidad3FocusGained

    private void cantidad3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad3FocusLost
        // TODO add your handling code here:
        if(cantidad3.getText().equals("")){
            cantidad3.setText("0");
        }
    }//GEN-LAST:event_cantidad3FocusLost

    private void cantidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad3ActionPerformed

    private void cantidad4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad4FocusGained
        // TODO add your handling code here:
        if(cantidad4.getText().equals("0")){
            cantidad4.setText("");}
    }//GEN-LAST:event_cantidad4FocusGained

    private void cantidad4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad4FocusLost
        // TODO add your handling code here:
        if(cantidad4.getText().equals("")){
            cantidad4.setText("0");
        }
    }//GEN-LAST:event_cantidad4FocusLost

    private void cantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad4ActionPerformed

    private void cantidad5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad5FocusGained
        // TODO add your handling code here:
        if(cantidad5.getText().equals("0")){
            cantidad5.setText("");}
    }//GEN-LAST:event_cantidad5FocusGained

    private void cantidad5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad5FocusLost
        // TODO add your handling code here:
        if(cantidad5.getText().equals("")){
            cantidad5.setText("0");
        }
    }//GEN-LAST:event_cantidad5FocusLost

    private void cantidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad5ActionPerformed

    private void cantidad6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad6FocusGained
        // TODO add your handling code here:
        if(cantidad6.getText().equals("0")){
            cantidad6.setText("");
        }
    }//GEN-LAST:event_cantidad6FocusGained

    private void cantidad6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad6FocusLost
        // TODO add your handling code here:
        if(cantidad6.getText().equals("")){
            cantidad6.setText("0");}

    }//GEN-LAST:event_cantidad6FocusLost

    private void cantidad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad6ActionPerformed

    private void cantidad7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad7FocusGained
        // TODO add your handling code here:
        if(cantidad7.getText().equals("0")){
            cantidad7.setText("");}
    }//GEN-LAST:event_cantidad7FocusGained

    private void cantidad7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad7FocusLost
        // TODO add your handling code here:
        if(cantidad7.getText().equals("")){
            cantidad7.setText("0");
        }
    }//GEN-LAST:event_cantidad7FocusLost

    private void cantidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad7ActionPerformed

    private void cantidad2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad2FocusGained
        // TODO add your handling code here:
        if(cantidad2.getText().equals("0")){
            cantidad2.setText("");}
    }//GEN-LAST:event_cantidad2FocusGained

    private void cantidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad2FocusLost
        // TODO add your handling code here:
        if(cantidad2.getText().equals("")){
            cantidad2.setText("0");
        }
    }//GEN-LAST:event_cantidad2FocusLost

    private void cantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminComida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel cant1;
    private javax.swing.JLabel cant2;
    private javax.swing.JLabel cant3;
    private javax.swing.JLabel cant4;
    private javax.swing.JLabel cant5;
    private javax.swing.JLabel cant6;
    private javax.swing.JLabel cant7;
    private javax.swing.JTextField cantidad1;
    private javax.swing.JTextField cantidad2;
    private javax.swing.JTextField cantidad3;
    private javax.swing.JTextField cantidad4;
    private javax.swing.JTextField cantidad5;
    private javax.swing.JTextField cantidad6;
    private javax.swing.JTextField cantidad7;
    private javax.swing.JTextArea comida1;
    private javax.swing.JTextArea comida2;
    private javax.swing.JTextArea comida3;
    private javax.swing.JTextArea comida4;
    private javax.swing.JTextArea comida5;
    private javax.swing.JTextArea comida6;
    private javax.swing.JTextArea comida7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea precioComida1;
    private javax.swing.JTextArea precioComida2;
    private javax.swing.JTextArea precioComida3;
    private javax.swing.JTextArea precioComida4;
    private javax.swing.JTextArea precioComida5;
    private javax.swing.JTextArea precioComida6;
    private javax.swing.JTextArea precioComida7;
    private javax.swing.JLabel simbolo1;
    private javax.swing.JLabel simbolo2;
    private javax.swing.JLabel simbolo3;
    private javax.swing.JLabel simbolo4;
    private javax.swing.JLabel simbolo5;
    private javax.swing.JLabel simbolo6;
    private javax.swing.JLabel simbolo7;
    private javax.swing.JLabel simbolo8;
    private javax.swing.JTextArea subComida1;
    private javax.swing.JTextArea subComida2;
    private javax.swing.JTextArea subComida3;
    private javax.swing.JTextArea subComida4;
    private javax.swing.JTextArea subComida5;
    private javax.swing.JTextArea subComida6;
    private javax.swing.JTextArea subComida7;
    private javax.swing.JLabel total2;
    // End of variables declaration//GEN-END:variables
}
