/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author reyna
 */
public class AdminBebida extends javax.swing.JFrame {
    Connection con = null;
    Statement stnt = null;
    /**
     * Creates new form AdminBebida
     */
    public AdminBebida() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        
    try {
    String url = "jdbc:mysql://localhost:3306/restaurante"; // direccion donde se encuentra la base de datos
    String usuario = "root"; // usuario de la gestion de base de datos
    String contraseña = "123"; // contraseña para entrar a la base de datos
                
    Class.forName("com.mysql.jdbc.Driver").newInstance(); // carga el driver para conectarce
    con = (Connection) DriverManager.getConnection(url,usuario,contraseña); // se conecta a la base de datos nuestro programa 
    if(con != null){
                System.out.println("Conexion Exitosa!");
            }else{
                System.out.println("Conexion Fallida!");                
            }
    }catch(Exception e){// excepciones en el caso de haber un error
         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null,e); 
    }

    stnt = con.createStatement(); 
    ResultSet rsl = stnt.executeQuery("SELECT * FROM producto WHERE id<10");
    if(rsl.next()){ 
    bebida1.setText(rsl.getString("nombre"));
    subBebida1.setText(rsl.getString("subNombre"));
    precioBebida1.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida2.setText(rsl.getString("nombre"));
    subBebida2.setText(rsl.getString("subNombre"));
    precioBebida2.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida3.setText(rsl.getString("nombre"));
    subBebida3.setText(rsl.getString("subNombre"));
    precioBebida3.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida4.setText(rsl.getString("nombre"));
    subBebida4.setText(rsl.getString("subNombre"));
    precioBebida4.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida5.setText(rsl.getString("nombre"));
    subBebida5.setText(rsl.getString("subNombre"));
    precioBebida5.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida6.setText(rsl.getString("nombre"));
    subBebida6.setText(rsl.getString("subNombre"));
    precioBebida6.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida7.setText(rsl.getString("nombre"));
    subBebida7.setText(rsl.getString("subNombre"));
    precioBebida7.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida8.setText(rsl.getString("nombre"));
    subBebida8.setText(rsl.getString("subNombre"));
    precioBebida8.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida9.setText(rsl.getString("nombre"));
    subBebida9.setText(rsl.getString("subNombre"));
    precioBebida9.setText(String.valueOf(rsl.getInt("precio")));
    }
    
    if(cantidad1.getText().equals("")){
            cantidad1.setText("0");
            }if(cantidad2.getText().equals("")){
            cantidad2.setText("0");
            }if(cantidad3.getText().equals("")){
            cantidad3.setText("0");
            }if(cantidad4.getText().equals("")){
            cantidad4.setText("0");
            }if(cantidad5.getText().equals("")){
            cantidad5.setText("0");
            }if(cantidad6.getText().equals("")){
            cantidad6.setText("0");
            }if(cantidad7.getText().equals("")){
            cantidad7.setText("0");
            }if(cantidad8.getText().equals("")){
            cantidad8.setText("0");
            }if(cantidad9.getText().equals("")){
            cantidad9.setText("0");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bebida1 = new javax.swing.JTextArea();
        bebida2 = new javax.swing.JTextArea();
        bebida3 = new javax.swing.JTextArea();
        bebida4 = new javax.swing.JTextArea();
        bebida5 = new javax.swing.JTextArea();
        bebida6 = new javax.swing.JTextArea();
        bebida7 = new javax.swing.JTextArea();
        bebida8 = new javax.swing.JTextArea();
        bebida9 = new javax.swing.JTextArea();
        precioBebida1 = new javax.swing.JTextArea();
        precioBebida2 = new javax.swing.JTextArea();
        precioBebida3 = new javax.swing.JTextArea();
        precioBebida4 = new javax.swing.JTextArea();
        precioBebida5 = new javax.swing.JTextArea();
        precioBebida6 = new javax.swing.JTextArea();
        precioBebida7 = new javax.swing.JTextArea();
        precioBebida8 = new javax.swing.JTextArea();
        precioBebida9 = new javax.swing.JTextArea();
        subBebida1 = new javax.swing.JTextArea();
        subBebida2 = new javax.swing.JTextArea();
        subBebida3 = new javax.swing.JTextArea();
        subBebida4 = new javax.swing.JTextArea();
        subBebida5 = new javax.swing.JTextArea();
        subBebida6 = new javax.swing.JTextArea();
        subBebida7 = new javax.swing.JTextArea();
        subBebida8 = new javax.swing.JTextArea();
        subBebida9 = new javax.swing.JTextArea();
        cantidad1 = new javax.swing.JTextField();
        cantidad2 = new javax.swing.JTextField();
        cantidad3 = new javax.swing.JTextField();
        cantidad4 = new javax.swing.JTextField();
        cantidad5 = new javax.swing.JTextField();
        cantidad6 = new javax.swing.JTextField();
        cantidad7 = new javax.swing.JTextField();
        cantidad8 = new javax.swing.JTextField();
        cantidad9 = new javax.swing.JTextField();
        agregar = new javax.swing.JLabel();
        cant1 = new javax.swing.JLabel();
        cant2 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        simbolo1 = new javax.swing.JLabel();
        simbolo2 = new javax.swing.JLabel();
        simbolo3 = new javax.swing.JLabel();
        simbolo4 = new javax.swing.JLabel();
        simbolo5 = new javax.swing.JLabel();
        simbolo6 = new javax.swing.JLabel();
        simbolo7 = new javax.swing.JLabel();
        simbolo8 = new javax.swing.JLabel();
        simbolo9 = new javax.swing.JLabel();
        simbolo10 = new javax.swing.JLabel();
        cant3 = new javax.swing.JLabel();
        cant10 = new javax.swing.JLabel();
        cant11 = new javax.swing.JLabel();
        cant12 = new javax.swing.JLabel();
        cant13 = new javax.swing.JLabel();
        cant14 = new javax.swing.JLabel();
        cant15 = new javax.swing.JLabel();
        cant4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 730));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 66, 73));
        jLabel4.setText("5.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 370, 60, 60);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 66, 73));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen4.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 20, 40, 100);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(34, 66, 73));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen4.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 10, 40, 110);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("BEBIDAS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 40, 230, 60);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 66, 73));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen4.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 20, 50, 120);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 66, 73));
        jLabel11.setText("1.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 170, 50, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 66, 73));
        jLabel13.setText("2.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 220, 50, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(34, 66, 73));
        jLabel14.setText("3.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 270, 60, 60);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(34, 66, 73));
        jLabel15.setText("4.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 320, 50, 60);

        bebida1.setColumns(20);
        bebida1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        bebida1.setForeground(new java.awt.Color(255, 102, 0));
        bebida1.setLineWrap(true);
        bebida1.setRows(5);
        bebida1.setText("Coca-Cola");
        bebida1.setBorder(null);
        bebida1.setCaretColor(new java.awt.Color(255, 255, 255));
        bebida1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        bebida1.setMinimumSize(new java.awt.Dimension(150, 20));
        bebida1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(bebida1);
        bebida1.setBounds(50, 180, 270, 30);

        bebida2.setColumns(20);
        bebida2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        bebida2.setForeground(new java.awt.Color(255, 102, 0));
        bebida2.setLineWrap(true);
        bebida2.setRows(5);
        bebida2.setText("Coca-Cola Zero");
        bebida2.setBorder(null);
        bebida2.setCaretColor(new java.awt.Color(255, 255, 255));
        bebida2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        bebida2.setMinimumSize(new java.awt.Dimension(150, 20));
        bebida2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(bebida2);
        bebida2.setBounds(50, 230, 270, 30);

        bebida3.setColumns(20);
        bebida3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        bebida3.setForeground(new java.awt.Color(255, 102, 0));
        bebida3.setLineWrap(true);
        bebida3.setRows(5);
        bebida3.setText("Fanta");
        bebida3.setBorder(null);
        bebida3.setCaretColor(new java.awt.Color(255, 255, 255));
        bebida3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        bebida3.setMinimumSize(new java.awt.Dimension(150, 20));
        bebida3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(bebida3);
        bebida3.setBounds(50, 280, 270, 30);

        bebida4.setColumns(20);
        bebida4.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        bebida4.setForeground(new java.awt.Color(255, 102, 0));
        bebida4.setLineWrap(true);
        bebida4.setRows(5);
        bebida4.setText("Fanta Zero");
        bebida4.setBorder(null);
        bebida4.setCaretColor(new java.awt.Color(255, 255, 255));
        bebida4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        bebida4.setMinimumSize(new java.awt.Dimension(150, 20));
        bebida4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(bebida4);
        bebida4.setBounds(50, 330, 270, 30);

        bebida5.setColumns(20);
        bebida5.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        bebida5.setForeground(new java.awt.Color(255, 102, 0));
        bebida5.setLineWrap(true);
        bebida5.setRows(5);
        bebida5.setText("Sprite\n");
        bebida5.setBorder(null);
        bebida5.setCaretColor(new java.awt.Color(255, 255, 255));
        bebida5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        bebida5.setMinimumSize(new java.awt.Dimension(150, 20));
        bebida5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(bebida5);
        bebida5.setBounds(50, 380, 270, 30);

        bebida6.setColumns(20);
        bebida6.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        bebida6.setForeground(new java.awt.Color(255, 102, 0));
        bebida6.setLineWrap(true);
        bebida6.setRows(5);
        bebida6.setText("Sprite Zero");
        bebida6.setBorder(null);
        bebida6.setCaretColor(new java.awt.Color(255, 255, 255));
        bebida6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        bebida6.setMinimumSize(new java.awt.Dimension(150, 20));
        bebida6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(bebida6);
        bebida6.setBounds(50, 430, 270, 30);

        bebida7.setColumns(20);
        bebida7.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        bebida7.setForeground(new java.awt.Color(255, 102, 0));
        bebida7.setLineWrap(true);
        bebida7.setRows(5);
        bebida7.setText("Jugo natural frambuesa");
        bebida7.setBorder(null);
        bebida7.setCaretColor(new java.awt.Color(255, 255, 255));
        bebida7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        bebida7.setMinimumSize(new java.awt.Dimension(150, 20));
        bebida7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(bebida7);
        bebida7.setBounds(50, 480, 270, 30);

        bebida8.setColumns(20);
        bebida8.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        bebida8.setForeground(new java.awt.Color(255, 102, 0));
        bebida8.setLineWrap(true);
        bebida8.setRows(5);
        bebida8.setText("Jugo natural melon");
        bebida8.setBorder(null);
        bebida8.setCaretColor(new java.awt.Color(255, 255, 255));
        bebida8.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        bebida8.setMinimumSize(new java.awt.Dimension(150, 20));
        bebida8.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(bebida8);
        bebida8.setBounds(50, 530, 270, 30);

        bebida9.setColumns(20);
        bebida9.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        bebida9.setForeground(new java.awt.Color(255, 102, 0));
        bebida9.setLineWrap(true);
        bebida9.setRows(5);
        bebida9.setText("Jugo natural piña");
        bebida9.setBorder(null);
        bebida9.setCaretColor(new java.awt.Color(255, 255, 255));
        bebida9.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        bebida9.setMinimumSize(new java.awt.Dimension(150, 20));
        bebida9.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(bebida9);
        bebida9.setBounds(50, 580, 270, 30);

        precioBebida1.setColumns(20);
        precioBebida1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioBebida1.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida1.setLineWrap(true);
        precioBebida1.setRows(5);
        precioBebida1.setText("1500");
        precioBebida1.setBorder(null);
        precioBebida1.setCaretColor(new java.awt.Color(255, 255, 255));
        precioBebida1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioBebida1.setMinimumSize(new java.awt.Dimension(150, 20));
        precioBebida1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioBebida1);
        precioBebida1.setBounds(350, 180, 70, 30);

        precioBebida2.setColumns(20);
        precioBebida2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioBebida2.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida2.setLineWrap(true);
        precioBebida2.setRows(5);
        precioBebida2.setText("1500");
        precioBebida2.setBorder(null);
        precioBebida2.setCaretColor(new java.awt.Color(255, 255, 255));
        precioBebida2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioBebida2.setMinimumSize(new java.awt.Dimension(150, 20));
        precioBebida2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioBebida2);
        precioBebida2.setBounds(350, 230, 70, 30);

        precioBebida3.setColumns(20);
        precioBebida3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioBebida3.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida3.setLineWrap(true);
        precioBebida3.setRows(5);
        precioBebida3.setText("1500");
        precioBebida3.setBorder(null);
        precioBebida3.setCaretColor(new java.awt.Color(255, 255, 255));
        precioBebida3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioBebida3.setMinimumSize(new java.awt.Dimension(150, 20));
        precioBebida3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioBebida3);
        precioBebida3.setBounds(350, 280, 70, 30);

        precioBebida4.setColumns(20);
        precioBebida4.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioBebida4.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida4.setLineWrap(true);
        precioBebida4.setRows(5);
        precioBebida4.setText("1500");
        precioBebida4.setBorder(null);
        precioBebida4.setCaretColor(new java.awt.Color(255, 255, 255));
        precioBebida4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioBebida4.setMinimumSize(new java.awt.Dimension(150, 20));
        precioBebida4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioBebida4);
        precioBebida4.setBounds(350, 330, 70, 30);

        precioBebida5.setColumns(20);
        precioBebida5.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioBebida5.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida5.setLineWrap(true);
        precioBebida5.setRows(5);
        precioBebida5.setText("1500");
        precioBebida5.setBorder(null);
        precioBebida5.setCaretColor(new java.awt.Color(255, 255, 255));
        precioBebida5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioBebida5.setMinimumSize(new java.awt.Dimension(150, 20));
        precioBebida5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioBebida5);
        precioBebida5.setBounds(350, 380, 70, 30);

        precioBebida6.setColumns(20);
        precioBebida6.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioBebida6.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida6.setLineWrap(true);
        precioBebida6.setRows(5);
        precioBebida6.setText("1500");
        precioBebida6.setBorder(null);
        precioBebida6.setCaretColor(new java.awt.Color(255, 255, 255));
        precioBebida6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioBebida6.setMinimumSize(new java.awt.Dimension(150, 20));
        precioBebida6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioBebida6);
        precioBebida6.setBounds(350, 430, 70, 30);

        precioBebida7.setColumns(20);
        precioBebida7.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioBebida7.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida7.setLineWrap(true);
        precioBebida7.setRows(5);
        precioBebida7.setText("2000");
        precioBebida7.setBorder(null);
        precioBebida7.setCaretColor(new java.awt.Color(255, 255, 255));
        precioBebida7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioBebida7.setMinimumSize(new java.awt.Dimension(150, 20));
        precioBebida7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioBebida7);
        precioBebida7.setBounds(350, 480, 70, 30);

        precioBebida8.setColumns(20);
        precioBebida8.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioBebida8.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida8.setLineWrap(true);
        precioBebida8.setRows(5);
        precioBebida8.setText("2000");
        precioBebida8.setBorder(null);
        precioBebida8.setCaretColor(new java.awt.Color(255, 255, 255));
        precioBebida8.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioBebida8.setMinimumSize(new java.awt.Dimension(150, 20));
        precioBebida8.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioBebida8);
        precioBebida8.setBounds(350, 530, 70, 30);

        precioBebida9.setColumns(20);
        precioBebida9.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        precioBebida9.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida9.setLineWrap(true);
        precioBebida9.setRows(5);
        precioBebida9.setText("2000");
        precioBebida9.setBorder(null);
        precioBebida9.setCaretColor(new java.awt.Color(255, 255, 255));
        precioBebida9.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        precioBebida9.setMinimumSize(new java.awt.Dimension(150, 20));
        precioBebida9.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(precioBebida9);
        precioBebida9.setBounds(350, 580, 70, 30);

        subBebida1.setColumns(20);
        subBebida1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida1.setForeground(new java.awt.Color(34, 66, 73));
        subBebida1.setLineWrap(true);
        subBebida1.setRows(5);
        subBebida1.setText("500 ml");
        subBebida1.setBorder(null);
        subBebida1.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida1.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida1.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida1);
        subBebida1.setBounds(50, 210, 250, 20);

        subBebida2.setColumns(20);
        subBebida2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida2.setForeground(new java.awt.Color(34, 66, 73));
        subBebida2.setLineWrap(true);
        subBebida2.setRows(5);
        subBebida2.setText("500ml\n");
        subBebida2.setBorder(null);
        subBebida2.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida2.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida2.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida2);
        subBebida2.setBounds(50, 260, 250, 20);

        subBebida3.setColumns(20);
        subBebida3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida3.setForeground(new java.awt.Color(34, 66, 73));
        subBebida3.setLineWrap(true);
        subBebida3.setRows(5);
        subBebida3.setText("500 ml");
        subBebida3.setBorder(null);
        subBebida3.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida3.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida3.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida3);
        subBebida3.setBounds(50, 310, 250, 20);

        subBebida4.setColumns(20);
        subBebida4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida4.setForeground(new java.awt.Color(34, 66, 73));
        subBebida4.setLineWrap(true);
        subBebida4.setRows(5);
        subBebida4.setText("500ml\n");
        subBebida4.setBorder(null);
        subBebida4.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida4.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida4.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida4);
        subBebida4.setBounds(50, 360, 250, 20);

        subBebida5.setColumns(20);
        subBebida5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida5.setForeground(new java.awt.Color(34, 66, 73));
        subBebida5.setLineWrap(true);
        subBebida5.setRows(5);
        subBebida5.setText("500 ml");
        subBebida5.setBorder(null);
        subBebida5.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida5.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida5.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida5);
        subBebida5.setBounds(50, 410, 250, 20);

        subBebida6.setColumns(20);
        subBebida6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida6.setForeground(new java.awt.Color(34, 66, 73));
        subBebida6.setLineWrap(true);
        subBebida6.setRows(5);
        subBebida6.setText("500ml\n");
        subBebida6.setBorder(null);
        subBebida6.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida6.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida6.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida6);
        subBebida6.setBounds(50, 460, 250, 20);

        subBebida7.setColumns(20);
        subBebida7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida7.setForeground(new java.awt.Color(34, 66, 73));
        subBebida7.setLineWrap(true);
        subBebida7.setRows(5);
        subBebida7.setText("500 ml");
        subBebida7.setBorder(null);
        subBebida7.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida7.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida7.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida7);
        subBebida7.setBounds(50, 510, 250, 20);

        subBebida8.setColumns(20);
        subBebida8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida8.setForeground(new java.awt.Color(34, 66, 73));
        subBebida8.setLineWrap(true);
        subBebida8.setRows(5);
        subBebida8.setText("500 ml");
        subBebida8.setBorder(null);
        subBebida8.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida8.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida8.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida8.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida8.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida8);
        subBebida8.setBounds(50, 560, 250, 20);

        subBebida9.setColumns(20);
        subBebida9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida9.setForeground(new java.awt.Color(34, 66, 73));
        subBebida9.setLineWrap(true);
        subBebida9.setRows(5);
        subBebida9.setText("500ml\n");
        subBebida9.setBorder(null);
        subBebida9.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida9.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida9.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida9.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida9.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida9);
        subBebida9.setBounds(50, 610, 250, 20);

        cantidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad1FocusLost(evt);
            }
        });
        cantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad1);
        cantidad1.setBounds(490, 180, 60, 30);

        cantidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad2FocusLost(evt);
            }
        });
        cantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad2ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad2);
        cantidad2.setBounds(490, 230, 60, 30);

        cantidad3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad3FocusLost(evt);
            }
        });
        cantidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad3ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad3);
        cantidad3.setBounds(490, 280, 60, 30);

        cantidad4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad4FocusLost(evt);
            }
        });
        cantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad4ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad4);
        cantidad4.setBounds(490, 330, 60, 30);

        cantidad5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad5FocusLost(evt);
            }
        });
        cantidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad5ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad5);
        cantidad5.setBounds(490, 380, 60, 30);

        cantidad6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad6FocusLost(evt);
            }
        });
        cantidad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad6ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad6);
        cantidad6.setBounds(490, 430, 60, 30);

        cantidad7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad7FocusLost(evt);
            }
        });
        cantidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad7ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad7);
        cantidad7.setBounds(490, 480, 60, 30);

        cantidad8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad8FocusLost(evt);
            }
        });
        cantidad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad8ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad8);
        cantidad8.setBounds(490, 530, 60, 30);

        cantidad9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad9FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad9FocusLost(evt);
            }
        });
        cantidad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad9ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad9);
        cantidad9.setBounds(490, 580, 60, 30);

        agregar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        agregar.setForeground(new java.awt.Color(34, 66, 73));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/agregar.png"))); // NOI18N
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(360, 640, 200, 80);

        cant1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cant1.setForeground(new java.awt.Color(34, 66, 73));
        cant1.setText("Agregar al inventario");
        getContentPane().add(cant1);
        cant1.setBounds(430, 130, 150, 40);

        cant2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant2.setForeground(new java.awt.Color(34, 66, 73));
        cant2.setText("Cant.");
        getContentPane().add(cant2);
        cant2.setBounds(430, 170, 70, 40);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(34, 66, 73));
        jLabel60.setText("6.");
        getContentPane().add(jLabel60);
        jLabel60.setBounds(20, 420, 50, 60);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(34, 66, 73));
        jLabel61.setText("7.");
        getContentPane().add(jLabel61);
        jLabel61.setBounds(20, 470, 50, 60);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(34, 66, 73));
        jLabel62.setText("8.");
        getContentPane().add(jLabel62);
        jLabel62.setBounds(20, 520, 60, 60);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(34, 66, 73));
        jLabel63.setText("9.");
        getContentPane().add(jLabel63);
        jLabel63.setBounds(20, 570, 50, 60);

        simbolo1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo1.setForeground(new java.awt.Color(255, 102, 0));
        simbolo1.setText("$");
        getContentPane().add(simbolo1);
        simbolo1.setBounds(330, 220, 20, 40);

        simbolo2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo2.setForeground(new java.awt.Color(255, 102, 0));
        simbolo2.setText("$");
        getContentPane().add(simbolo2);
        simbolo2.setBounds(330, 270, 20, 40);

        simbolo3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo3.setForeground(new java.awt.Color(255, 102, 0));
        simbolo3.setText("$");
        getContentPane().add(simbolo3);
        simbolo3.setBounds(330, 320, 20, 40);

        simbolo4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo4.setForeground(new java.awt.Color(255, 102, 0));
        simbolo4.setText("$");
        getContentPane().add(simbolo4);
        simbolo4.setBounds(330, 370, 20, 40);

        simbolo5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo5.setForeground(new java.awt.Color(255, 102, 0));
        simbolo5.setText("$");
        getContentPane().add(simbolo5);
        simbolo5.setBounds(330, 420, 20, 40);

        simbolo6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo6.setForeground(new java.awt.Color(255, 102, 0));
        simbolo6.setText("$");
        getContentPane().add(simbolo6);
        simbolo6.setBounds(330, 470, 20, 40);

        simbolo7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo7.setForeground(new java.awt.Color(255, 102, 0));
        simbolo7.setText("$");
        getContentPane().add(simbolo7);
        simbolo7.setBounds(330, 170, 20, 40);

        simbolo8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo8.setForeground(new java.awt.Color(255, 102, 0));
        simbolo8.setText("$");
        getContentPane().add(simbolo8);
        simbolo8.setBounds(330, 470, 20, 40);

        simbolo9.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo9.setForeground(new java.awt.Color(255, 102, 0));
        simbolo9.setText("$");
        getContentPane().add(simbolo9);
        simbolo9.setBounds(330, 520, 20, 40);

        simbolo10.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo10.setForeground(new java.awt.Color(255, 102, 0));
        simbolo10.setText("$");
        getContentPane().add(simbolo10);
        simbolo10.setBounds(330, 570, 20, 40);

        cant3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant3.setForeground(new java.awt.Color(34, 66, 73));
        cant3.setText("Cant.");
        getContentPane().add(cant3);
        cant3.setBounds(430, 220, 70, 40);

        cant10.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant10.setForeground(new java.awt.Color(34, 66, 73));
        cant10.setText("Cant.");
        getContentPane().add(cant10);
        cant10.setBounds(430, 320, 70, 40);

        cant11.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant11.setForeground(new java.awt.Color(34, 66, 73));
        cant11.setText("Cant.");
        getContentPane().add(cant11);
        cant11.setBounds(430, 370, 70, 40);

        cant12.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant12.setForeground(new java.awt.Color(34, 66, 73));
        cant12.setText("Cant.");
        getContentPane().add(cant12);
        cant12.setBounds(430, 420, 70, 40);

        cant13.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant13.setForeground(new java.awt.Color(34, 66, 73));
        cant13.setText("Cant.");
        getContentPane().add(cant13);
        cant13.setBounds(430, 470, 70, 40);

        cant14.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant14.setForeground(new java.awt.Color(34, 66, 73));
        cant14.setText("Cant.");
        getContentPane().add(cant14);
        cant14.setBounds(430, 520, 70, 40);

        cant15.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant15.setForeground(new java.awt.Color(34, 66, 73));
        cant15.setText("Cant.");
        getContentPane().add(cant15);
        cant15.setBounds(430, 570, 70, 40);

        cant4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant4.setForeground(new java.awt.Color(34, 66, 73));
        cant4.setText("Cant.");
        getContentPane().add(cant4);
        cant4.setBounds(430, 270, 70, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/93b5f9913d2e4316cd6e541c67b9aed0.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 600, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        try {
            // TODO add your handling code here:
            stnt = con.createStatement();
            
            ResultSet rsl = stnt.executeQuery("SELECT * FROM producto WHERE nombre =  '"+ bebida1.getText()+"' AND subNombre = '"+subBebida1.getText()+"' AND precio = "+ precioBebida1.getText()+ "");
            if(!rsl.next()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ bebida1.getText()+"', subNombre = '"+subBebida1.getText()+"', precio = "+ precioBebida1.getText()+ " WHERE id = 1");               
            JOptionPane.showMessageDialog(this, "cambio realizado con exito");
            }
            
           
            ResultSet rs2 = stnt.executeQuery("SELECT * FROM producto WHERE nombre =  '"+ bebida2.getText()+"' AND subNombre = '"+subBebida2.getText()+"' AND precio = "+ precioBebida2.getText()+ "");
            if(!rs2.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ bebida2.getText()+"', subNombre = '"+subBebida2.getText()+"', precio = "+ precioBebida2.getText()+ " WHERE id = 2");               
            JOptionPane.showMessageDialog(this, "cambio realizado con exito");
            }
            
            
            ResultSet rs3 = stnt.executeQuery("SELECT * FROM producto WHERE nombre = '"+ bebida3.getText()+"' AND subNombre = '"+subBebida3.getText()+"' AND precio = "+ precioBebida3.getText()+ "");
            if(!rs3.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ bebida3.getText()+"', subNombre = '"+subBebida3.getText()+"', precio = "+ precioBebida3.getText()+ " WHERE id = 3");               
            JOptionPane.showMessageDialog(this, "cambio realizado con exito");
            }
            
            
            ResultSet rs4 = stnt.executeQuery("SELECT * FROM producto WHERE nombre ='"+ bebida4.getText()+"' AND subNombre = '"+subBebida4.getText()+"' AND precio = "+ precioBebida4.getText()+ "");
            if(!rs4.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ bebida4.getText()+"', subNombre = '"+subBebida4.getText()+"', precio = "+ precioBebida4.getText()+ " WHERE id = 4");               
            JOptionPane.showMessageDialog(this, "cambio realizado con exito");
            }
            
            
            ResultSet rs5 = stnt.executeQuery("SELECT * FROM producto WHERE nombre = '"+ bebida5.getText()+"' AND subNombre = '"+subBebida5.getText()+"' AND precio = "+ precioBebida5.getText()+ "");
            if(!rs5.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ bebida5.getText()+"', subNombre = '"+subBebida5.getText()+"', precio = "+ precioBebida5.getText()+ " WHERE id = 5");               
            JOptionPane.showMessageDialog(this, "cambio realizado con exito");
            }
            
            ResultSet rs6 = stnt.executeQuery("SELECT * FROM producto WHERE nombre = '"+ bebida6.getText()+"' AND subNombre = '"+subBebida6.getText()+"' AND precio = "+ precioBebida6.getText()+ "");
            if(!rs6.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ bebida6.getText()+"', subNombre = '"+subBebida6.getText()+"', precio = "+ precioBebida6.getText()+ " WHERE id = 6");               
            JOptionPane.showMessageDialog(this, "cambio realizado con exito");
            }
            
            ResultSet rs7 = stnt.executeQuery("SELECT * FROM producto WHERE nombre = '"+ bebida7.getText()+"' AND subNombre = '"+subBebida7.getText()+"' AND precio = "+ precioBebida7.getText()+ "");
            if(!rs7.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ bebida7.getText()+"', subNombre = '"+subBebida7.getText()+"', precio = "+ precioBebida7.getText()+ " WHERE id = 7");               
            JOptionPane.showMessageDialog(this, "cambio realizado con exito");
            }
            
            ResultSet rs8 = stnt.executeQuery("SELECT * FROM producto WHERE nombre = '"+ bebida8.getText()+"' AND subNombre = '"+subBebida8.getText()+"' AND precio = "+ precioBebida8.getText()+ "");
            if(!rs8.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ bebida8.getText()+"', subNombre = '"+subBebida8.getText()+"', precio = "+ precioBebida8.getText()+ " WHERE id = 8");               
            JOptionPane.showMessageDialog(this, "cambio realizado con exito");
            }
            
            ResultSet rs9 = stnt.executeQuery("SELECT * FROM producto WHERE nombre = '"+ bebida9.getText()+"' AND subNombre = '"+subBebida9.getText()+"' AND precio = "+ precioBebida9.getText()+ "");
            if(!rs9.first()){
            stnt.executeUpdate("UPDATE producto SET nombre = '"+ bebida9.getText()+"', subNombre = '"+subBebida9.getText()+"', precio = "+ precioBebida9.getText()+ " WHERE id = 9");               
            JOptionPane.showMessageDialog(this, "cambio realizado con exito");
            }        
          
                    
            if(Integer.parseInt(cantidad1.getText())>0){
            ResultSet rsa = stnt.executeQuery("CALL ingresoInventario("+cantidad1.getText()+",1)");
            }
            if(Integer.parseInt(cantidad2.getText())>0){
            ResultSet rsb = stnt.executeQuery("CALL ingresoInventario("+cantidad2.getText()+",2)");
            }
            if(Integer.parseInt(cantidad3.getText())>0){
            ResultSet rsc = stnt.executeQuery("CALL ingresoInventario("+cantidad3.getText()+",3)");
            }
           if(Integer.parseInt(cantidad4.getText())>0){
            ResultSet rsd = stnt.executeQuery("CALL ingresoInventario("+cantidad4.getText()+",4)");
            }                       
           if(Integer.parseInt(cantidad5.getText())>0){
            ResultSet rse = stnt.executeQuery("CALL ingresoInventario("+cantidad5.getText()+",5)");
            }            
           if(Integer.parseInt(cantidad6.getText())>0){
            ResultSet rsf = stnt.executeQuery("CALL ingresoInventario("+cantidad6.getText()+",6)");
            }
           if(Integer.parseInt(cantidad7.getText())>0){
            ResultSet rsg = stnt.executeQuery("CALL ingresoInventario("+cantidad7.getText()+",7)");
            } 
           if(Integer.parseInt(cantidad8.getText())>0){
            ResultSet rsh = stnt.executeQuery("CALL ingresoInventario("+cantidad8.getText()+",8)");
            }
           if(Integer.parseInt(cantidad9.getText())>0){
            ResultSet rsi = stnt.executeQuery("CALL ingresoInventario("+cantidad9.getText()+",9)");
            }           
        } catch (SQLException ex) {
            Logger.getLogger(AdminBebida.class.getName()).log(Level.SEVERE, null, ex);         
        }   
        AdminMenu go = new AdminMenu();
        go.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agregarMouseClicked

    private void cantidad1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad1FocusGained
        // TODO add your handling code here:
        if(cantidad1.getText().equals("0")){
            cantidad1.setText("");
        }

    }//GEN-LAST:event_cantidad1FocusGained

    private void cantidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad1FocusLost
        // TODO add your handling code here:
        if(cantidad1.getText().equals("")){
            cantidad1.setText("0");
        }
    }//GEN-LAST:event_cantidad1FocusLost

    private void cantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad1ActionPerformed

    private void cantidad2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad2FocusGained
        // TODO add your handling code here:
        if(cantidad2.getText().equals("0")){
            cantidad2.setText("");
        }
    }//GEN-LAST:event_cantidad2FocusGained

    private void cantidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad2FocusLost
        // TODO add your handling code here:
        if(cantidad2.getText().equals("")){
            cantidad2.setText("0");
        }
    }//GEN-LAST:event_cantidad2FocusLost

    private void cantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad2ActionPerformed

    private void cantidad3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad3FocusGained
        // TODO add your handling code here:
        if(cantidad3.getText().equals("0")){
            cantidad3.setText("");
        }
    }//GEN-LAST:event_cantidad3FocusGained

    private void cantidad3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad3FocusLost
        // TODO add your handling code here:
        if(cantidad3.getText().equals("")){
            cantidad3.setText("0");
        }
    }//GEN-LAST:event_cantidad3FocusLost

    private void cantidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad3ActionPerformed

    private void cantidad4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad4FocusGained
        // TODO add your handling code here:
        if(cantidad4.getText().equals("0")){
            cantidad4.setText("");
        }
    }//GEN-LAST:event_cantidad4FocusGained

    private void cantidad4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad4FocusLost
        // TODO add your handling code here:
        if(cantidad4.getText().equals("")){
            cantidad4.setText("0");
        }
    }//GEN-LAST:event_cantidad4FocusLost

    private void cantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad4ActionPerformed

    private void cantidad5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad5FocusGained
        // TODO add your handling code here:
        if(cantidad5.getText().equals("0")){
            cantidad5.setText("");
        }
    }//GEN-LAST:event_cantidad5FocusGained

    private void cantidad5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad5FocusLost
        // TODO add your handling code here:
        if(cantidad5.getText().equals("")){
            cantidad5.setText("0");
        }
    }//GEN-LAST:event_cantidad5FocusLost

    private void cantidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad5ActionPerformed

    private void cantidad6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad6FocusGained
        // TODO add your handling code here:
        if(cantidad6.getText().equals("0")){
            cantidad6.setText("");
        }
    }//GEN-LAST:event_cantidad6FocusGained

    private void cantidad6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad6FocusLost
        // TODO add your handling code here:
        if(cantidad6.getText().equals("")){
            cantidad6.setText("0");
        }
    }//GEN-LAST:event_cantidad6FocusLost

    private void cantidad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad6ActionPerformed

    private void cantidad7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad7FocusGained
        // TODO add your handling code here:
        if(cantidad7.getText().equals("0")){
            cantidad7.setText("");
        }
    }//GEN-LAST:event_cantidad7FocusGained

    private void cantidad7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad7FocusLost
        // TODO add your handling code here:
        if(cantidad7.getText().equals("")){
            cantidad7.setText("0");
        }
    }//GEN-LAST:event_cantidad7FocusLost

    private void cantidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad7ActionPerformed

    private void cantidad8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad8FocusGained
        // TODO add your handling code here:
        if(cantidad8.getText().equals("0")){
            cantidad8.setText("");
        }
    }//GEN-LAST:event_cantidad8FocusGained

    private void cantidad8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad8FocusLost
        // TODO add your handling code here:
        if(cantidad8.getText().equals("")){
            cantidad8.setText("0");
        }
    }//GEN-LAST:event_cantidad8FocusLost

    private void cantidad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad8ActionPerformed

    private void cantidad9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad9FocusGained
        // TODO add your handling code here:
        if(cantidad9.getText().equals("0")){
            cantidad9.setText("");
        }

    }//GEN-LAST:event_cantidad9FocusGained

    private void cantidad9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad9FocusLost
        // TODO add your handling code here:
        if(cantidad9.getText().equals("")){
            cantidad9.setText("0");
        }
    }//GEN-LAST:event_cantidad9FocusLost

    private void cantidad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          
                try {
                    new AdminBebida().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminBebida.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    public static javax.swing.JTextArea bebida1;
    public static javax.swing.JTextArea bebida2;
    public static javax.swing.JTextArea bebida3;
    public static javax.swing.JTextArea bebida4;
    public static javax.swing.JTextArea bebida5;
    public static javax.swing.JTextArea bebida6;
    public static javax.swing.JTextArea bebida7;
    public static javax.swing.JTextArea bebida8;
    public static javax.swing.JTextArea bebida9;
    private javax.swing.JLabel cant1;
    private javax.swing.JLabel cant10;
    private javax.swing.JLabel cant11;
    private javax.swing.JLabel cant12;
    private javax.swing.JLabel cant13;
    private javax.swing.JLabel cant14;
    private javax.swing.JLabel cant15;
    private javax.swing.JLabel cant2;
    private javax.swing.JLabel cant3;
    private javax.swing.JLabel cant4;
    private javax.swing.JTextField cantidad1;
    private javax.swing.JTextField cantidad2;
    private javax.swing.JTextField cantidad3;
    private javax.swing.JTextField cantidad4;
    private javax.swing.JTextField cantidad5;
    private javax.swing.JTextField cantidad6;
    private javax.swing.JTextField cantidad7;
    private javax.swing.JTextField cantidad8;
    private javax.swing.JTextField cantidad9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextArea precioBebida1;
    public static javax.swing.JTextArea precioBebida2;
    public static javax.swing.JTextArea precioBebida3;
    public static javax.swing.JTextArea precioBebida4;
    public static javax.swing.JTextArea precioBebida5;
    public static javax.swing.JTextArea precioBebida6;
    public static javax.swing.JTextArea precioBebida7;
    public static javax.swing.JTextArea precioBebida8;
    public static javax.swing.JTextArea precioBebida9;
    private javax.swing.JLabel simbolo1;
    private javax.swing.JLabel simbolo10;
    private javax.swing.JLabel simbolo2;
    private javax.swing.JLabel simbolo3;
    private javax.swing.JLabel simbolo4;
    private javax.swing.JLabel simbolo5;
    private javax.swing.JLabel simbolo6;
    private javax.swing.JLabel simbolo7;
    private javax.swing.JLabel simbolo8;
    private javax.swing.JLabel simbolo9;
    public static javax.swing.JTextArea subBebida1;
    public static javax.swing.JTextArea subBebida2;
    public static javax.swing.JTextArea subBebida3;
    public static javax.swing.JTextArea subBebida4;
    public static javax.swing.JTextArea subBebida5;
    public static javax.swing.JTextArea subBebida6;
    public static javax.swing.JTextArea subBebida7;
    public static javax.swing.JTextArea subBebida8;
    public static javax.swing.JTextArea subBebida9;
    // End of variables declaration//GEN-END:variables
}
