/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reyna
 */
public class DetallesAdmin extends javax.swing.JFrame {
    Connection con = null;
    Statement stnt = null;
    /**
     * Creates new form DetallesAdmin
     */
    public DetallesAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        
        
               try {
    String url = "jdbc:mysql://localhost:3306/restaurante"; // direccion donde se encuentra la base de datos
    String usuario = "root"; // usuario de la gestion de base de datos
    String contraseña = "123"; // contraseña para entrar a la base de datos
                
    Class.forName("com.mysql.jdbc.Driver").newInstance(); // carga el driver para conectarce
    con = (Connection) DriverManager.getConnection(url,usuario,contraseña); // se conecta a la base de datos nuestro programa 
    if(con != null){
                System.out.println("Conexion Exitosa!");
            }else{
                System.out.println("Conexion Fallida!");                
            }
    
    
    }catch(Exception e){// excepciones en el caso de haber un error
         Logger.getLogger(DetallesAdmin.class.getName()).log(Level.SEVERE, null,e); 
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 800));
        getContentPane().setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 0));
        jLabel20.setText("Usuarios");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20);
        jLabel20.setBounds(800, 620, 260, 60);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 0));
        jLabel18.setText("Administradores");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18);
        jLabel18.setBounds(800, 560, 260, 60);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 66, 73));
        jLabel11.setText("VOLVER");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(880, 710, 180, 50);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText("Historial cambios de usuario");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 620, 530, 60);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 0));
        jLabel17.setText("Stock de productos");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 680, 260, 60);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("Historial cambios de comidas");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 560, 550, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(34, 66, 73));
        jLabel7.setText("DETALLE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 40, 260, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 1040, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/93b5f9913d2e4316cd6e541c67b9aed0.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1310, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        
  
        
        DefaultTableModel modeloTabla = new DefaultTableModel();
        jTable1.setModel(modeloTabla);
        modeloTabla.setColumnIdentifiers(new Object[]{"tipo","Nombre","Sub Nombre","precio","fecha"});//

        try { // condicion en caso de error
        stnt = con.createStatement();
        ResultSet rsl = stnt.executeQuery("SELECT * FROM registroHistorico");
       
         while(rsl.next()){
                modeloTabla.addRow(new Object[]{rsl.getInt("producto_id_fk"),rsl.getString("nombre"),rsl.getString("subNombre"),rsl.getInt("precio"),rsl.getString("fecha")});}
            }catch (SQLException ex) {
         Logger.getLogger(DetallesAdmin.class.getName()).log(Level.SEVERE, null, ex);

        }
        
        
    
    
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        
               
        DefaultTableModel modeloTabla = new DefaultTableModel();
        jTable1.setModel(modeloTabla);
        modeloTabla.setColumnIdentifiers(new Object[]{"stock","nombre"});//

        try { // condicion en caso de error
        stnt = con.createStatement();
        ResultSet rsl = stnt.executeQuery("SELECT stock, nombre FROM producto");
       
         while(rsl.next()){
                modeloTabla.addRow(new Object[]{rsl.getInt("stock"),rsl.getString("nombre")});}
            }catch (SQLException ex) {
         Logger.getLogger(DetallesAdmin.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
                
        DefaultTableModel modeloTabla = new DefaultTableModel();
        jTable1.setModel(modeloTabla);
        modeloTabla.setColumnIdentifiers(new Object[]{"tipo","Nombre","apellido","correo","fecha"});//

        try { // condicion en caso de error
        stnt = con.createStatement();
        ResultSet rsl = stnt.executeQuery("SELECT * FROM historialUsuario");
       
         while(rsl.next()){
                modeloTabla.addRow(new Object[]{rsl.getInt("id"),rsl.getString("nombre"),rsl.getString("apellido"),rsl.getString("correo"),rsl.getString("fecha")});}
            }catch (SQLException ex) {
        Logger.getLogger(DetallesAdmin.class.getName()).log(Level.SEVERE, null, ex);

        }
        
        
        
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        AdminMenu go = new AdminMenu();
        go.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
                
        DefaultTableModel modeloTabla = new DefaultTableModel();
        jTable1.setModel(modeloTabla);
        modeloTabla.setColumnIdentifiers(new Object[]{"id","rut","nombre","apellido","correo"});//
        try {
         stnt = con.createStatement();
         ResultSet rsl = stnt.executeQuery("SELECT * FROM usuario WHERE tipoUsuario_id_fk = 1");
       
         while(rsl.next()){
                modeloTabla.addRow(new Object[]{rsl.getInt("id"),rsl.getString("nombre"),rsl.getString("apellido"),rsl.getString("correo")});}

            
        } catch (SQLException ex) {
            Logger.getLogger(DetallesAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modeloTabla = new DefaultTableModel();
        jTable1.setModel(modeloTabla);
        modeloTabla.setColumnIdentifiers(new Object[]{"id","rut","nombre","apellido","correo"});//
        try {
         stnt = con.createStatement();
         ResultSet rsl = stnt.executeQuery("SELECT * FROM usuario WHERE tipoUsuario_id_fk = 2");
       
         while(rsl.next()){
                modeloTabla.addRow(new Object[]{rsl.getInt("id"),rsl.getString("nombre"),rsl.getString("apellido"),rsl.getString("correo")});}

            
        } catch (SQLException ex) {
            Logger.getLogger(DetallesAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
