/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author reyna
 */
public class MenuBebidas extends javax.swing.JFrame {
    Connection con = null;
    Statement stnt = null;
    String rut = Login.jTextField1.getText();
   
    /**
     * Creates new form MenuBebidas
     */
    public MenuBebidas() throws SQLException {
        initComponents(); 
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        limpiar();
    try {
    String url = "jdbc:mysql://localhost:3306/restaurante"; // direccion donde se encuentra la base de datos
    String usuario = "root"; // usuario de la gestion de base de datos
    String contraseña = "123"; // contraseña para entrar a la base de datos
                
    Class.forName("com.mysql.jdbc.Driver").newInstance(); // carga el driver para conectarce
    con = (Connection) DriverManager.getConnection(url,usuario,contraseña); // se conecta a la base de datos nuestro programa 
    if(con != null){
                System.out.println("Conexion Exitosa!");
            }else{
                System.out.println("Conexion Fallida!");                
            }
    }catch(Exception e){// excepciones en el caso de haber un error
         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null,e); 
    }
    
    stnt = con.createStatement(); 
    ResultSet rsl = stnt.executeQuery("SELECT * FROM producto");
    if(rsl.next()){ 
    bebida1.setText(rsl.getString("nombre"));
    subBebida1.setText(rsl.getString("subNombre"));
    precioBebida1.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida2.setText(rsl.getString("nombre"));
    subBebida2.setText(rsl.getString("subNombre"));
    precioBebida2.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida3.setText(rsl.getString("nombre"));
    subBebida3.setText(rsl.getString("subNombre"));
    precioBebida3.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida4.setText(rsl.getString("nombre"));
    subBebida4.setText(rsl.getString("subNombre"));
    precioBebida4.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida5.setText(rsl.getString("nombre"));
    subBebida5.setText(rsl.getString("subNombre"));
    precioBebida5.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida6.setText(rsl.getString("nombre"));
    subBebida6.setText(rsl.getString("subNombre"));
    precioBebida6.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida7.setText(rsl.getString("nombre"));
    subBebida7.setText(rsl.getString("subNombre"));
    precioBebida7.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida8.setText(rsl.getString("nombre"));
    subBebida8.setText(rsl.getString("subNombre"));
    precioBebida8.setText(String.valueOf(rsl.getInt("precio")));
    }if(rsl.next()){ 
    bebida9.setText(rsl.getString("nombre"));
    subBebida9.setText(rsl.getString("subNombre"));
    precioBebida9.setText(String.valueOf(rsl.getInt("precio")));
    }
    
                 
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        bebida1 = new javax.swing.JLabel();
        bebida2 = new javax.swing.JLabel();
        bebida3 = new javax.swing.JLabel();
        bebida4 = new javax.swing.JLabel();
        bebida5 = new javax.swing.JLabel();
        bebida6 = new javax.swing.JLabel();
        bebida7 = new javax.swing.JLabel();
        bebida8 = new javax.swing.JLabel();
        bebida9 = new javax.swing.JLabel();
        agregar = new javax.swing.JLabel();
        subBebida1 = new javax.swing.JTextArea();
        subBebida2 = new javax.swing.JTextArea();
        subBebida3 = new javax.swing.JTextArea();
        subBebida4 = new javax.swing.JTextArea();
        subBebida5 = new javax.swing.JTextArea();
        subBebida6 = new javax.swing.JTextArea();
        subBebida7 = new javax.swing.JTextArea();
        subBebida8 = new javax.swing.JTextArea();
        subBebida9 = new javax.swing.JTextArea();
        cantidad1 = new javax.swing.JTextField();
        cantidad2 = new javax.swing.JTextField();
        cantidad3 = new javax.swing.JTextField();
        cantidad4 = new javax.swing.JTextField();
        cantidad5 = new javax.swing.JTextField();
        cantidad6 = new javax.swing.JTextField();
        cantidad7 = new javax.swing.JTextField();
        cantidad8 = new javax.swing.JTextField();
        cantidad9 = new javax.swing.JTextField();
        precioBebida1 = new javax.swing.JLabel();
        precioBebida2 = new javax.swing.JLabel();
        precioBebida3 = new javax.swing.JLabel();
        precioBebida4 = new javax.swing.JLabel();
        precioBebida5 = new javax.swing.JLabel();
        precioBebida6 = new javax.swing.JLabel();
        precioBebida7 = new javax.swing.JLabel();
        precioBebida8 = new javax.swing.JLabel();
        precioBebida9 = new javax.swing.JLabel();
        cant1 = new javax.swing.JLabel();
        cant2 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        simbolo1 = new javax.swing.JLabel();
        simbolo2 = new javax.swing.JLabel();
        simbolo3 = new javax.swing.JLabel();
        simbolo4 = new javax.swing.JLabel();
        simbolo5 = new javax.swing.JLabel();
        simbolo6 = new javax.swing.JLabel();
        simbolo7 = new javax.swing.JLabel();
        simbolo8 = new javax.swing.JLabel();
        simbolo9 = new javax.swing.JLabel();
        simbolo10 = new javax.swing.JLabel();
        cant3 = new javax.swing.JLabel();
        cant4 = new javax.swing.JLabel();
        cant5 = new javax.swing.JLabel();
        cant6 = new javax.swing.JLabel();
        cant7 = new javax.swing.JLabel();
        cant8 = new javax.swing.JLabel();
        cant9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 770));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 66, 73));
        jLabel4.setText("5.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 360, 60, 60);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 66, 73));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen4.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 10, 40, 100);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(34, 66, 73));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen4.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 10, 40, 110);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("BEBIDAS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 50, 230, 60);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 66, 73));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen4.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 20, 50, 120);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 66, 73));
        jLabel11.setText("1.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 160, 50, 60);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 66, 73));
        jLabel13.setText("2.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 210, 50, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(34, 66, 73));
        jLabel14.setText("3.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 260, 60, 60);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(34, 66, 73));
        jLabel15.setText("4.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 310, 50, 60);

        total1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total1.setForeground(new java.awt.Color(34, 66, 73));
        getContentPane().add(total1);
        total1.setBounds(130, 670, 140, 40);

        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total.setForeground(new java.awt.Color(34, 66, 73));
        total.setText("TOTAL  $");
        getContentPane().add(total);
        total.setBounds(20, 670, 130, 40);

        bebida1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida1.setForeground(new java.awt.Color(255, 102, 0));
        bebida1.setText("Coca-Cola");
        getContentPane().add(bebida1);
        bebida1.setBounds(50, 160, 220, 60);

        bebida2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida2.setForeground(new java.awt.Color(255, 102, 0));
        bebida2.setText("Coca-Cola Zero");
        getContentPane().add(bebida2);
        bebida2.setBounds(50, 210, 250, 60);

        bebida3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida3.setForeground(new java.awt.Color(255, 102, 0));
        bebida3.setText("Fanta");
        getContentPane().add(bebida3);
        bebida3.setBounds(50, 260, 160, 60);

        bebida4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida4.setForeground(new java.awt.Color(255, 102, 0));
        bebida4.setText("Fanta Zero");
        getContentPane().add(bebida4);
        bebida4.setBounds(50, 310, 200, 60);

        bebida5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida5.setForeground(new java.awt.Color(255, 102, 0));
        bebida5.setText("Sprite");
        getContentPane().add(bebida5);
        bebida5.setBounds(50, 360, 180, 60);

        bebida6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida6.setForeground(new java.awt.Color(255, 102, 0));
        bebida6.setText("Sprite Zero");
        getContentPane().add(bebida6);
        bebida6.setBounds(50, 410, 200, 60);

        bebida7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida7.setForeground(new java.awt.Color(255, 102, 0));
        bebida7.setText("Jugo natural frambuesa");
        getContentPane().add(bebida7);
        bebida7.setBounds(50, 470, 230, 40);

        bebida8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida8.setForeground(new java.awt.Color(255, 102, 0));
        bebida8.setText("Jugo natural melon");
        getContentPane().add(bebida8);
        bebida8.setBounds(50, 520, 190, 40);

        bebida9.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida9.setForeground(new java.awt.Color(255, 102, 0));
        bebida9.setText("Jugo natural piña");
        getContentPane().add(bebida9);
        bebida9.setBounds(50, 570, 280, 40);

        agregar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        agregar.setForeground(new java.awt.Color(34, 66, 73));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/agregar.png"))); // NOI18N
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(310, 660, 200, 80);

        subBebida1.setEditable(false);
        subBebida1.setColumns(20);
        subBebida1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida1.setForeground(new java.awt.Color(34, 66, 73));
        subBebida1.setLineWrap(true);
        subBebida1.setRows(5);
        subBebida1.setText("500 ml");
        subBebida1.setBorder(null);
        subBebida1.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida1.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida1.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida1);
        subBebida1.setBounds(50, 200, 250, 50);

        subBebida2.setEditable(false);
        subBebida2.setColumns(20);
        subBebida2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida2.setForeground(new java.awt.Color(34, 66, 73));
        subBebida2.setLineWrap(true);
        subBebida2.setRows(5);
        subBebida2.setText("500ml\n");
        subBebida2.setBorder(null);
        subBebida2.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida2.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida2.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida2);
        subBebida2.setBounds(50, 250, 250, 40);

        subBebida3.setEditable(false);
        subBebida3.setColumns(20);
        subBebida3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida3.setForeground(new java.awt.Color(34, 66, 73));
        subBebida3.setLineWrap(true);
        subBebida3.setRows(5);
        subBebida3.setText("500 ml");
        subBebida3.setBorder(null);
        subBebida3.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida3.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida3.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida3);
        subBebida3.setBounds(50, 300, 250, 50);

        subBebida4.setEditable(false);
        subBebida4.setColumns(20);
        subBebida4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida4.setForeground(new java.awt.Color(34, 66, 73));
        subBebida4.setLineWrap(true);
        subBebida4.setRows(5);
        subBebida4.setText("500 ml");
        subBebida4.setBorder(null);
        subBebida4.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida4.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida4.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida4);
        subBebida4.setBounds(50, 350, 250, 40);

        subBebida5.setEditable(false);
        subBebida5.setColumns(20);
        subBebida5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida5.setForeground(new java.awt.Color(34, 66, 73));
        subBebida5.setLineWrap(true);
        subBebida5.setRows(5);
        subBebida5.setText("500 ml");
        subBebida5.setBorder(null);
        subBebida5.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida5.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida5.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida5);
        subBebida5.setBounds(50, 400, 250, 40);

        subBebida6.setEditable(false);
        subBebida6.setColumns(20);
        subBebida6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida6.setForeground(new java.awt.Color(34, 66, 73));
        subBebida6.setLineWrap(true);
        subBebida6.setRows(5);
        subBebida6.setText("500 ml");
        subBebida6.setBorder(null);
        subBebida6.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida6.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida6.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida6);
        subBebida6.setBounds(50, 450, 250, 50);

        subBebida7.setEditable(false);
        subBebida7.setColumns(20);
        subBebida7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida7.setForeground(new java.awt.Color(34, 66, 73));
        subBebida7.setLineWrap(true);
        subBebida7.setRows(5);
        subBebida7.setText("500 ml");
        subBebida7.setBorder(null);
        subBebida7.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida7.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida7.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida7);
        subBebida7.setBounds(50, 500, 250, 40);

        subBebida8.setEditable(false);
        subBebida8.setColumns(20);
        subBebida8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida8.setForeground(new java.awt.Color(34, 66, 73));
        subBebida8.setLineWrap(true);
        subBebida8.setRows(5);
        subBebida8.setText("500 ml");
        subBebida8.setBorder(null);
        subBebida8.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida8.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida8.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida8.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida8.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida8);
        subBebida8.setBounds(50, 550, 250, 40);

        subBebida9.setEditable(false);
        subBebida9.setColumns(20);
        subBebida9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subBebida9.setForeground(new java.awt.Color(34, 66, 73));
        subBebida9.setLineWrap(true);
        subBebida9.setRows(5);
        subBebida9.setText("500 ml");
        subBebida9.setBorder(null);
        subBebida9.setCaretColor(new java.awt.Color(255, 255, 255));
        subBebida9.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subBebida9.setMinimumSize(new java.awt.Dimension(150, 20));
        subBebida9.setPreferredSize(new java.awt.Dimension(280, 100));
        subBebida9.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subBebida9);
        subBebida9.setBounds(50, 600, 250, 40);

        cantidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad1FocusLost(evt);
            }
        });
        cantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad1);
        cantidad1.setBounds(490, 180, 60, 30);

        cantidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad2FocusLost(evt);
            }
        });
        cantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad2ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad2);
        cantidad2.setBounds(490, 230, 60, 30);

        cantidad3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad3FocusLost(evt);
            }
        });
        cantidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad3ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad3);
        cantidad3.setBounds(490, 280, 60, 30);

        cantidad4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad4FocusLost(evt);
            }
        });
        cantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad4ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad4);
        cantidad4.setBounds(490, 330, 60, 30);

        cantidad5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad5FocusLost(evt);
            }
        });
        cantidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad5ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad5);
        cantidad5.setBounds(490, 380, 60, 30);

        cantidad6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad6FocusLost(evt);
            }
        });
        cantidad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad6ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad6);
        cantidad6.setBounds(490, 430, 60, 30);

        cantidad7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad7FocusLost(evt);
            }
        });
        cantidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad7ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad7);
        cantidad7.setBounds(490, 480, 60, 30);

        cantidad8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad8FocusLost(evt);
            }
        });
        cantidad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad8ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad8);
        cantidad8.setBounds(490, 530, 60, 30);

        cantidad9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad9FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad9FocusLost(evt);
            }
        });
        cantidad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad9ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad9);
        cantidad9.setBounds(490, 580, 60, 30);

        precioBebida1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida1.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida1.setText("1500");
        getContentPane().add(precioBebida1);
        precioBebida1.setBounds(350, 170, 70, 40);

        precioBebida2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida2.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida2.setText("1500");
        getContentPane().add(precioBebida2);
        precioBebida2.setBounds(350, 220, 70, 40);

        precioBebida3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida3.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida3.setText("1500");
        getContentPane().add(precioBebida3);
        precioBebida3.setBounds(350, 270, 70, 40);

        precioBebida4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida4.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida4.setText("1500");
        getContentPane().add(precioBebida4);
        precioBebida4.setBounds(350, 320, 70, 40);

        precioBebida5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida5.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida5.setText("1500");
        getContentPane().add(precioBebida5);
        precioBebida5.setBounds(350, 370, 70, 40);

        precioBebida6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida6.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida6.setText("1500");
        getContentPane().add(precioBebida6);
        precioBebida6.setBounds(350, 420, 70, 40);

        precioBebida7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida7.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida7.setText("1500");
        getContentPane().add(precioBebida7);
        precioBebida7.setBounds(350, 470, 70, 40);

        precioBebida8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida8.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida8.setText("2000");
        getContentPane().add(precioBebida8);
        precioBebida8.setBounds(350, 520, 70, 40);

        precioBebida9.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida9.setForeground(new java.awt.Color(255, 102, 0));
        precioBebida9.setText("2000");
        getContentPane().add(precioBebida9);
        precioBebida9.setBounds(350, 570, 70, 40);

        cant1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant1.setForeground(new java.awt.Color(34, 66, 73));
        cant1.setText("Cant.");
        getContentPane().add(cant1);
        cant1.setBounds(430, 170, 70, 40);

        cant2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant2.setForeground(new java.awt.Color(34, 66, 73));
        cant2.setText("Cant.");
        getContentPane().add(cant2);
        cant2.setBounds(430, 220, 70, 40);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(34, 66, 73));
        jLabel60.setText("6.");
        getContentPane().add(jLabel60);
        jLabel60.setBounds(20, 410, 50, 60);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(34, 66, 73));
        jLabel61.setText("7.");
        getContentPane().add(jLabel61);
        jLabel61.setBounds(20, 460, 50, 60);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(34, 66, 73));
        jLabel62.setText("8.");
        getContentPane().add(jLabel62);
        jLabel62.setBounds(20, 510, 60, 60);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(34, 66, 73));
        jLabel63.setText("9.");
        getContentPane().add(jLabel63);
        jLabel63.setBounds(20, 560, 50, 60);

        simbolo1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo1.setForeground(new java.awt.Color(255, 102, 0));
        simbolo1.setText("$");
        getContentPane().add(simbolo1);
        simbolo1.setBounds(330, 220, 20, 40);

        simbolo2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo2.setForeground(new java.awt.Color(255, 102, 0));
        simbolo2.setText("$");
        getContentPane().add(simbolo2);
        simbolo2.setBounds(330, 270, 20, 40);

        simbolo3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo3.setForeground(new java.awt.Color(255, 102, 0));
        simbolo3.setText("$");
        getContentPane().add(simbolo3);
        simbolo3.setBounds(330, 320, 20, 40);

        simbolo4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo4.setForeground(new java.awt.Color(255, 102, 0));
        simbolo4.setText("$");
        getContentPane().add(simbolo4);
        simbolo4.setBounds(330, 370, 20, 40);

        simbolo5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo5.setForeground(new java.awt.Color(255, 102, 0));
        simbolo5.setText("$");
        getContentPane().add(simbolo5);
        simbolo5.setBounds(330, 420, 20, 40);

        simbolo6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo6.setForeground(new java.awt.Color(255, 102, 0));
        simbolo6.setText("$");
        getContentPane().add(simbolo6);
        simbolo6.setBounds(330, 470, 20, 40);

        simbolo7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo7.setForeground(new java.awt.Color(255, 102, 0));
        simbolo7.setText("$");
        getContentPane().add(simbolo7);
        simbolo7.setBounds(330, 170, 20, 40);

        simbolo8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo8.setForeground(new java.awt.Color(255, 102, 0));
        simbolo8.setText("$");
        getContentPane().add(simbolo8);
        simbolo8.setBounds(330, 470, 20, 40);

        simbolo9.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo9.setForeground(new java.awt.Color(255, 102, 0));
        simbolo9.setText("$");
        getContentPane().add(simbolo9);
        simbolo9.setBounds(330, 520, 20, 40);

        simbolo10.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo10.setForeground(new java.awt.Color(255, 102, 0));
        simbolo10.setText("$");
        getContentPane().add(simbolo10);
        simbolo10.setBounds(330, 570, 20, 40);

        cant3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant3.setForeground(new java.awt.Color(34, 66, 73));
        cant3.setText("Cant.");
        getContentPane().add(cant3);
        cant3.setBounds(430, 270, 70, 40);

        cant4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant4.setForeground(new java.awt.Color(34, 66, 73));
        cant4.setText("Cant.");
        getContentPane().add(cant4);
        cant4.setBounds(430, 320, 70, 40);

        cant5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant5.setForeground(new java.awt.Color(34, 66, 73));
        cant5.setText("Cant.");
        getContentPane().add(cant5);
        cant5.setBounds(430, 370, 70, 40);

        cant6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant6.setForeground(new java.awt.Color(34, 66, 73));
        cant6.setText("Cant.");
        getContentPane().add(cant6);
        cant6.setBounds(430, 420, 70, 40);

        cant7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant7.setForeground(new java.awt.Color(34, 66, 73));
        cant7.setText("Cant.");
        getContentPane().add(cant7);
        cant7.setBounds(430, 470, 70, 40);

        cant8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant8.setForeground(new java.awt.Color(34, 66, 73));
        cant8.setText("Cant.");
        getContentPane().add(cant8);
        cant8.setBounds(430, 520, 70, 40);

        cant9.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant9.setForeground(new java.awt.Color(34, 66, 73));
        cant9.setText("Cant.");
        getContentPane().add(cant9);
        cant9.setBounds(430, 570, 70, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/93b5f9913d2e4316cd6e541c67b9aed0.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -20, 690, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        // TODO add your handling code here:
        int precioTotal1 = ((Integer.parseInt(precioBebida1.getText())*Integer.parseInt(cantidad1.getText())));
        int precioTotal2 = ((Integer.parseInt(precioBebida2.getText())*Integer.parseInt(cantidad2.getText())));
        int precioTotal3 = ((Integer.parseInt(precioBebida3.getText())*Integer.parseInt(cantidad3.getText())));
        int precioTotal4 = ((Integer.parseInt(precioBebida4.getText())*Integer.parseInt(cantidad4.getText())));
        int precioTotal5 = ((Integer.parseInt(precioBebida5.getText())*Integer.parseInt(cantidad5.getText())));
        int precioTotal6 = ((Integer.parseInt(precioBebida6.getText())*Integer.parseInt(cantidad6.getText())));
        int precioTotal7 = ((Integer.parseInt(precioBebida7.getText())*Integer.parseInt(cantidad7.getText())));
        int precioTotal8 = ((Integer.parseInt(precioBebida8.getText())*Integer.parseInt(cantidad8.getText())));
        int precioTotal9 = ((Integer.parseInt(precioBebida9.getText())*Integer.parseInt(cantidad9.getText())));
        
                try {
                stnt = con.createStatement();
                ResultSet rs = null;
                if(Integer.parseInt(cantidad1.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 1 && stock<"+cantidad1.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + rs.getInt("stock") + "en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),1,"
                                             +cantidad1.getText()+","+precioTotal1+")");}
                }if(Integer.parseInt(cantidad2.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 2 && stock<"+cantidad2.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + rs.getInt("stock") + "en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),2,"
                                             +cantidad2.getText()+","+precioTotal2+")");} 
                }if(Integer.parseInt(cantidad3.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 3 && stock<"+cantidad3.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + rs.getInt("stock") + "en " + rs.getString("nombre"),"Error",2);
                    }else{
                     rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),3,"
                                             +cantidad3.getText()+","+precioTotal3+")");}          
                }if(Integer.parseInt(cantidad4.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 4 && stock<"+cantidad4.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + rs.getInt("stock") + "en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),4,"
                                             +cantidad4.getText()+","+precioTotal4+")");}           
                }if(Integer.parseInt(cantidad5.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 5 && stock<"+cantidad5.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + rs.getInt("stock") + "en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),5,"
                                             +cantidad5.getText()+","+precioTotal5+")");}           
                }if(Integer.parseInt(cantidad6.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 6 && stock<"+cantidad6.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + rs.getInt("stock") + "en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),6,"
                                             +cantidad6.getText()+","+precioTotal6+")");}           
                }if(Integer.parseInt(cantidad7.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 7 && stock<"+cantidad7.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + rs.getInt("stock") + "en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),7,"
                                             +cantidad7.getText()+","+precioTotal7+")");}        
                }if(Integer.parseInt(cantidad8.getText())>0){            
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 8 && stock<"+cantidad8.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + rs.getInt("stock") + "en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),8,"
                                             +cantidad8.getText()+","+precioTotal8+")");}          
                }if(Integer.parseInt(cantidad9.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 9 && stock<"+cantidad9.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + rs.getInt("stock") + "en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),9,"
                                             +cantidad9.getText()+","+precioTotal9+")");}
                    }
                
        }catch(Exception e){
            
        }
                
        
        
        
        Carta go = new Carta();
        go.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agregarMouseClicked

    private void cantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad1ActionPerformed

    private void cantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad2ActionPerformed

    private void cantidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad3ActionPerformed

    private void cantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad4ActionPerformed

    private void cantidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad5ActionPerformed

    private void cantidad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad6ActionPerformed

    private void cantidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad7ActionPerformed

    private void cantidad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad8ActionPerformed

    private void cantidad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad9ActionPerformed

    private void cantidad1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad1FocusGained
        // TODO add your handling code here:           
            if(cantidad1.getText().equals("0")){
               cantidad1.setText("");
            }
        
    }//GEN-LAST:event_cantidad1FocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
            if(cantidad1.getText().equals("")){
            cantidad1.setText("0");
            }if(cantidad2.getText().equals("")){
            cantidad2.setText("0");
            }if(cantidad3.getText().equals("")){
            cantidad3.setText("0");
            }if(cantidad4.getText().equals("")){
            cantidad4.setText("0");
            }if(cantidad5.getText().equals("")){
            cantidad5.setText("0");
            }if(cantidad6.getText().equals("")){
            cantidad6.setText("0");
            }if(cantidad7.getText().equals("")){
            cantidad7.setText("0");
            }if(cantidad8.getText().equals("")){
            cantidad8.setText("0");
            }if(cantidad9.getText().equals("")){
            cantidad9.setText("0");}
            
       if(Integer.parseInt(cantidad1.getText())>=0){   
       int a = Integer.parseInt(precioBebida1.getText());
       int b = Integer.parseInt(precioBebida2.getText());
       int c = Integer.parseInt(precioBebida3.getText());
       int d = Integer.parseInt(precioBebida4.getText());
       int e = Integer.parseInt(precioBebida5.getText());
       int f = Integer.parseInt(precioBebida6.getText());
       int g = Integer.parseInt(precioBebida7.getText());
       int h = Integer.parseInt(precioBebida8.getText());
       int i = Integer.parseInt(precioBebida9.getText());
       int aa = Integer.parseInt(cantidad1.getText());
       int bb = Integer.parseInt(cantidad2.getText());
       int cc = Integer.parseInt(cantidad3.getText());
       int dd = Integer.parseInt(cantidad4.getText());
       int ee = Integer.parseInt(cantidad5.getText());
       int ff = Integer.parseInt(cantidad6.getText());
       int gg = Integer.parseInt(cantidad7.getText());
       int hh = Integer.parseInt(cantidad8.getText());
       int ii = Integer.parseInt(cantidad9.getText());
       total1.setText(String.valueOf((a*aa)+(b*bb)+(c*cc)+(d*dd)+(e*ee)+(f*ff)+(g*gg)+(h*hh)+(i*ii)));
       }
    }//GEN-LAST:event_formMouseMoved

    private void cantidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad1FocusLost
        // TODO add your handling code here:
            if(cantidad1.getText().equals("")){
            cantidad1.setText("0");
            }
    }//GEN-LAST:event_cantidad1FocusLost

    private void cantidad2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad2FocusGained
        // TODO add your handling code here:
            if(cantidad2.getText().equals("0")){
            cantidad2.setText("");
            }
    }//GEN-LAST:event_cantidad2FocusGained

    private void cantidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad2FocusLost
        // TODO add your handling code here:
            if(cantidad2.getText().equals("")){
            cantidad2.setText("0");
            }
    }//GEN-LAST:event_cantidad2FocusLost

    private void cantidad3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad3FocusGained
        // TODO add your handling code here:
            if(cantidad3.getText().equals("0")){
            cantidad3.setText("");
            }
    }//GEN-LAST:event_cantidad3FocusGained

    private void cantidad3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad3FocusLost
        // TODO add your handling code here:
            if(cantidad3.getText().equals("")){
            cantidad3.setText("0");
            }
    }//GEN-LAST:event_cantidad3FocusLost

    private void cantidad4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad4FocusGained
        // TODO add your handling code here:
            if(cantidad4.getText().equals("0")){
            cantidad4.setText("");
            }
    }//GEN-LAST:event_cantidad4FocusGained

    private void cantidad4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad4FocusLost
        // TODO add your handling code here:
            if(cantidad4.getText().equals("")){
            cantidad4.setText("0");
            }
    }//GEN-LAST:event_cantidad4FocusLost

    private void cantidad5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad5FocusGained
        // TODO add your handling code here:
            if(cantidad5.getText().equals("0")){
            cantidad5.setText("");
            }
    }//GEN-LAST:event_cantidad5FocusGained

    private void cantidad5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad5FocusLost
        // TODO add your handling code here:
            if(cantidad5.getText().equals("")){
            cantidad5.setText("0");
            }
    }//GEN-LAST:event_cantidad5FocusLost

    private void cantidad6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad6FocusGained
        // TODO add your handling code here:
            if(cantidad6.getText().equals("0")){
            cantidad6.setText("");
            }
    }//GEN-LAST:event_cantidad6FocusGained

    private void cantidad6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad6FocusLost
        // TODO add your handling code here:
            if(cantidad6.getText().equals("")){
            cantidad6.setText("0");
            }
    }//GEN-LAST:event_cantidad6FocusLost

    private void cantidad7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad7FocusGained
        // TODO add your handling code here:
            if(cantidad7.getText().equals("0")){
            cantidad7.setText("");
            }
    }//GEN-LAST:event_cantidad7FocusGained

    private void cantidad7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad7FocusLost
        // TODO add your handling code here:
            if(cantidad7.getText().equals("")){
            cantidad7.setText("0");
            }
    }//GEN-LAST:event_cantidad7FocusLost

    private void cantidad8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad8FocusGained
        // TODO add your handling code here:
            if(cantidad8.getText().equals("0")){
            cantidad8.setText("");
            }
    }//GEN-LAST:event_cantidad8FocusGained

    private void cantidad8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad8FocusLost
        // TODO add your handling code here:
            if(cantidad8.getText().equals("")){
            cantidad8.setText("0");
            }
    }//GEN-LAST:event_cantidad8FocusLost

    private void cantidad9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad9FocusGained
        // TODO add your handling code here:            
            if(cantidad9.getText().equals("0")){
            cantidad9.setText("");
            }
        
    }//GEN-LAST:event_cantidad9FocusGained

    private void cantidad9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad9FocusLost
        // TODO add your handling code here:
            if(cantidad9.getText().equals("")){
            cantidad9.setText("0");
            }
    }//GEN-LAST:event_cantidad9FocusLost

    public void limpiar(){
       cantidad1.setText("0");
       cantidad2.setText("0");
       cantidad3.setText("0");
       cantidad4.setText("0");
       cantidad5.setText("0");
       cantidad6.setText("0");
       cantidad7.setText("0");
       cantidad8.setText("0");
       cantidad9.setText("0");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuBebidas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MenuBebidas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    public static javax.swing.JLabel bebida1;
    public static javax.swing.JLabel bebida2;
    public static javax.swing.JLabel bebida3;
    public static javax.swing.JLabel bebida4;
    public static javax.swing.JLabel bebida5;
    public static javax.swing.JLabel bebida6;
    public static javax.swing.JLabel bebida7;
    public static javax.swing.JLabel bebida8;
    public static javax.swing.JLabel bebida9;
    private javax.swing.JLabel cant1;
    private javax.swing.JLabel cant2;
    private javax.swing.JLabel cant3;
    private javax.swing.JLabel cant4;
    private javax.swing.JLabel cant5;
    private javax.swing.JLabel cant6;
    private javax.swing.JLabel cant7;
    private javax.swing.JLabel cant8;
    private javax.swing.JLabel cant9;
    public static javax.swing.JTextField cantidad1;
    public static javax.swing.JTextField cantidad2;
    public static javax.swing.JTextField cantidad3;
    public static javax.swing.JTextField cantidad4;
    public static javax.swing.JTextField cantidad5;
    public static javax.swing.JTextField cantidad6;
    public static javax.swing.JTextField cantidad7;
    public static javax.swing.JTextField cantidad8;
    public static javax.swing.JTextField cantidad9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel precioBebida1;
    public static javax.swing.JLabel precioBebida2;
    public static javax.swing.JLabel precioBebida3;
    public static javax.swing.JLabel precioBebida4;
    public static javax.swing.JLabel precioBebida5;
    public static javax.swing.JLabel precioBebida6;
    public static javax.swing.JLabel precioBebida7;
    public static javax.swing.JLabel precioBebida8;
    public static javax.swing.JLabel precioBebida9;
    private javax.swing.JLabel simbolo1;
    private javax.swing.JLabel simbolo10;
    private javax.swing.JLabel simbolo2;
    private javax.swing.JLabel simbolo3;
    private javax.swing.JLabel simbolo4;
    private javax.swing.JLabel simbolo5;
    private javax.swing.JLabel simbolo6;
    private javax.swing.JLabel simbolo7;
    private javax.swing.JLabel simbolo8;
    private javax.swing.JLabel simbolo9;
    public static javax.swing.JTextArea subBebida1;
    public static javax.swing.JTextArea subBebida2;
    public static javax.swing.JTextArea subBebida3;
    public static javax.swing.JTextArea subBebida4;
    public static javax.swing.JTextArea subBebida5;
    public static javax.swing.JTextArea subBebida6;
    public static javax.swing.JTextArea subBebida7;
    public static javax.swing.JTextArea subBebida8;
    public static javax.swing.JTextArea subBebida9;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    // End of variables declaration//GEN-END:variables
}
