/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import javafx.scene.control.ScrollPane;

/**
 *
 * @author reyna
 */
public class MenuComida extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuComida() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        menos3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        val3 = new javax.swing.JLabel();
        mas2 = new javax.swing.JLabel();
        precioComida3 = new javax.swing.JLabel();
        precioComida4 = new javax.swing.JLabel();
        comida7 = new javax.swing.JLabel();
        comida6 = new javax.swing.JLabel();
        jTextArea9 = new javax.swing.JTextArea();
        menos4 = new javax.swing.JLabel();
        jTextArea8 = new javax.swing.JTextArea();
        val4 = new javax.swing.JLabel();
        mas3 = new javax.swing.JLabel();
        precioComida2 = new javax.swing.JLabel();
        menos2 = new javax.swing.JLabel();
        val2 = new javax.swing.JLabel();
        mas4 = new javax.swing.JLabel();
        precioComida5 = new javax.swing.JLabel();
        menos5 = new javax.swing.JLabel();
        val5 = new javax.swing.JLabel();
        comida5 = new javax.swing.JLabel();
        jTextArea7 = new javax.swing.JTextArea();
        mas5 = new javax.swing.JLabel();
        precioComida6 = new javax.swing.JLabel();
        menos6 = new javax.swing.JLabel();
        val6 = new javax.swing.JLabel();
        mas6 = new javax.swing.JLabel();
        comida4 = new javax.swing.JLabel();
        jTextArea6 = new javax.swing.JTextArea();
        comida1 = new javax.swing.JLabel();
        precioComida1 = new javax.swing.JLabel();
        menos1 = new javax.swing.JLabel();
        val1 = new javax.swing.JLabel();
        mas1 = new javax.swing.JLabel();
        comida3 = new javax.swing.JLabel();
        jTextArea5 = new javax.swing.JTextArea();
        precioComida7 = new javax.swing.JLabel();
        menos7 = new javax.swing.JLabel();
        val7 = new javax.swing.JLabel();
        mas7 = new javax.swing.JLabel();
        comida2 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea4 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 770));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 66, 73));
        jLabel4.setText("5.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 530, 60, 60);

        menos3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos3.setForeground(new java.awt.Color(34, 66, 73));
        menos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos3MouseClicked(evt);
            }
        });
        getContentPane().add(menos3);
        menos3.setBounds(520, 360, 20, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(34, 66, 73));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen2.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 10, 130, 130);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("COMIDA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 50, 230, 60);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 66, 73));
        jLabel11.setText("1.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 150, 50, 60);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 66, 73));
        jLabel13.setText("2.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 240, 50, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(34, 66, 73));
        jLabel14.setText("3.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 340, 60, 60);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(34, 66, 73));
        jLabel15.setText("4.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 430, 50, 60);

        val3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val3.setForeground(new java.awt.Color(34, 66, 73));
        val3.setText("0");
        val3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val3);
        val3.setBounds(550, 340, 40, 60);

        mas2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas2.setForeground(new java.awt.Color(34, 66, 73));
        mas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas2MouseClicked(evt);
            }
        });
        getContentPane().add(mas2);
        mas2.setBounds(580, 260, 20, 20);

        precioComida3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioComida3.setForeground(new java.awt.Color(255, 102, 0));
        precioComida3.setText("$8.990");
        getContentPane().add(precioComida3);
        precioComida3.setBounds(430, 350, 70, 40);

        precioComida4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioComida4.setForeground(new java.awt.Color(255, 102, 0));
        precioComida4.setText("$11.990");
        getContentPane().add(precioComida4);
        precioComida4.setBounds(420, 440, 100, 40);

        comida7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        comida7.setForeground(new java.awt.Color(255, 102, 0));
        comida7.setText("PARRILLA PERSONAL");
        getContentPane().add(comida7);
        comida7.setBounds(60, 730, 220, 40);

        comida6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        comida6.setForeground(new java.awt.Color(255, 102, 0));
        comida6.setText("POLLO A LA BRASA");
        getContentPane().add(comida6);
        comida6.setBounds(60, 630, 340, 40);

        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea9.setForeground(new java.awt.Color(1, 30, 68));
        jTextArea9.setLineWrap(true);
        jTextArea9.setRows(5);
        jTextArea9.setText("Nuestra deliciosa parrilla incluye bife ancho de res, pechuga de pollo, carne de cerdo, \nsalchicha farnkfuter y papas fritas.");
        jTextArea9.setBorder(null);
        jTextArea9.setCaretColor(new java.awt.Color(1, 30, 68));
        jTextArea9.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        jTextArea9.setEnabled(false);
        jTextArea9.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextArea9.setPreferredSize(new java.awt.Dimension(280, 100));
        jTextArea9.setSelectionColor(new java.awt.Color(1, 30, 68));
        getContentPane().add(jTextArea9);
        jTextArea9.setBounds(60, 760, 300, 110);

        menos4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos4.setForeground(new java.awt.Color(34, 66, 73));
        menos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos4MouseClicked(evt);
            }
        });
        getContentPane().add(menos4);
        menos4.setBounds(520, 450, 30, 20);

        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(1, 30, 68));
        jTextArea8.setLineWrap(true);
        jTextArea8.setRows(5);
        jTextArea8.setText("1/4 de pollo acompañado con papas fritas.");
        jTextArea8.setBorder(null);
        jTextArea8.setCaretColor(new java.awt.Color(1, 30, 68));
        jTextArea8.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        jTextArea8.setEnabled(false);
        jTextArea8.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextArea8.setPreferredSize(new java.awt.Dimension(280, 100));
        jTextArea8.setSelectionColor(new java.awt.Color(1, 30, 68));
        getContentPane().add(jTextArea8);
        jTextArea8.setBounds(60, 660, 300, 110);

        val4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val4.setForeground(new java.awt.Color(34, 66, 73));
        val4.setText("0");
        val4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val4);
        val4.setBounds(550, 430, 50, 60);

        mas3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas3.setForeground(new java.awt.Color(34, 66, 73));
        mas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas3MouseClicked(evt);
            }
        });
        getContentPane().add(mas3);
        mas3.setBounds(580, 360, 20, 20);

        precioComida2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioComida2.setForeground(new java.awt.Color(255, 102, 0));
        precioComida2.setText("$9.990");
        getContentPane().add(precioComida2);
        precioComida2.setBounds(430, 250, 70, 40);

        menos2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos2.setForeground(new java.awt.Color(34, 66, 73));
        menos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos2MouseClicked(evt);
            }
        });
        getContentPane().add(menos2);
        menos2.setBounds(520, 260, 20, 20);

        val2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val2.setForeground(new java.awt.Color(34, 66, 73));
        val2.setText("0");
        val2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val2);
        val2.setBounds(550, 240, 40, 60);

        mas4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas4.setForeground(new java.awt.Color(34, 66, 73));
        mas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas4MouseClicked(evt);
            }
        });
        getContentPane().add(mas4);
        mas4.setBounds(580, 450, 30, 20);

        precioComida5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioComida5.setForeground(new java.awt.Color(255, 102, 0));
        precioComida5.setText("$7.990");
        getContentPane().add(precioComida5);
        precioComida5.setBounds(430, 540, 70, 40);

        menos5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos5.setForeground(new java.awt.Color(34, 66, 73));
        menos5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos5MouseClicked(evt);
            }
        });
        getContentPane().add(menos5);
        menos5.setBounds(520, 550, 20, 20);

        val5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val5.setForeground(new java.awt.Color(34, 66, 73));
        val5.setText("0");
        val5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val5);
        val5.setBounds(550, 530, 40, 60);

        comida5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        comida5.setForeground(new java.awt.Color(255, 102, 0));
        comida5.setText("PECHUGA PARRILLERA");
        getContentPane().add(comida5);
        comida5.setBounds(60, 540, 290, 40);

        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(1, 30, 68));
        jTextArea7.setLineWrap(true);
        jTextArea7.setRows(5);
        jTextArea7.setText("Pechuga acompañada con arroz y ensalada\nmixta.");
        jTextArea7.setBorder(null);
        jTextArea7.setCaretColor(new java.awt.Color(1, 30, 68));
        jTextArea7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        jTextArea7.setEnabled(false);
        jTextArea7.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextArea7.setPreferredSize(new java.awt.Dimension(280, 100));
        jTextArea7.setSelectionColor(new java.awt.Color(1, 30, 68));
        getContentPane().add(jTextArea7);
        jTextArea7.setBounds(60, 570, 300, 110);

        mas5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas5.setForeground(new java.awt.Color(34, 66, 73));
        mas5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas5MouseClicked(evt);
            }
        });
        getContentPane().add(mas5);
        mas5.setBounds(580, 550, 20, 20);

        precioComida6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioComida6.setForeground(new java.awt.Color(255, 102, 0));
        precioComida6.setText("$8.990");
        getContentPane().add(precioComida6);
        precioComida6.setBounds(430, 630, 70, 40);

        menos6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos6.setForeground(new java.awt.Color(34, 66, 73));
        menos6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos6MouseClicked(evt);
            }
        });
        getContentPane().add(menos6);
        menos6.setBounds(520, 640, 20, 20);

        val6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val6.setForeground(new java.awt.Color(34, 66, 73));
        val6.setText("0");
        val6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val6);
        val6.setBounds(550, 620, 40, 60);

        mas6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas6.setForeground(new java.awt.Color(34, 66, 73));
        mas6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas6MouseClicked(evt);
            }
        });
        getContentPane().add(mas6);
        mas6.setBounds(580, 640, 20, 20);

        comida4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        comida4.setForeground(new java.awt.Color(255, 102, 0));
        comida4.setText("BIFE CORLEONE");
        getContentPane().add(comida4);
        comida4.setBounds(60, 440, 220, 40);

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(1, 30, 68));
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setText("Bife ancho de res, bañado en nuestra cremosa\nsalsa de pimienta negra y fetuccinnis bañados en mantequilla y salvia.");
        jTextArea6.setBorder(null);
        jTextArea6.setCaretColor(new java.awt.Color(1, 30, 68));
        jTextArea6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        jTextArea6.setEnabled(false);
        jTextArea6.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextArea6.setPreferredSize(new java.awt.Dimension(280, 100));
        jTextArea6.setSelectionColor(new java.awt.Color(1, 30, 68));
        getContentPane().add(jTextArea6);
        jTextArea6.setBounds(60, 470, 310, 110);

        comida1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        comida1.setForeground(new java.awt.Color(255, 102, 0));
        comida1.setText("LOMO MANTARO");
        getContentPane().add(comida1);
        comida1.setBounds(60, 160, 220, 40);

        precioComida1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioComida1.setForeground(new java.awt.Color(255, 102, 0));
        precioComida1.setText("$10.990");
        getContentPane().add(precioComida1);
        precioComida1.setBounds(420, 160, 100, 40);

        menos1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos1.setForeground(new java.awt.Color(34, 66, 73));
        menos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos1MouseClicked(evt);
            }
        });
        getContentPane().add(menos1);
        menos1.setBounds(520, 170, 20, 20);

        val1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val1.setForeground(new java.awt.Color(34, 66, 73));
        val1.setText("0");
        val1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val1);
        val1.setBounds(550, 160, 40, 40);

        mas1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas1.setForeground(new java.awt.Color(34, 66, 73));
        mas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas1MouseClicked(evt);
            }
        });
        getContentPane().add(mas1);
        mas1.setBounds(580, 170, 20, 20);

        comida3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        comida3.setForeground(new java.awt.Color(255, 102, 0));
        comida3.setText("BIFE BRAVO");
        getContentPane().add(comida3);
        comida3.setBounds(60, 350, 220, 40);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(1, 30, 68));
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("Bife ancho de res acompañado de nuestras   inigualables papas bravas.");
        jTextArea5.setBorder(null);
        jTextArea5.setCaretColor(new java.awt.Color(1, 30, 68));
        jTextArea5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        jTextArea5.setEnabled(false);
        jTextArea5.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextArea5.setPreferredSize(new java.awt.Dimension(280, 100));
        jTextArea5.setSelectionColor(new java.awt.Color(1, 30, 68));
        getContentPane().add(jTextArea5);
        jTextArea5.setBounds(60, 380, 300, 110);

        precioComida7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioComida7.setForeground(new java.awt.Color(255, 102, 0));
        precioComida7.setText("$9.990");
        getContentPane().add(precioComida7);
        precioComida7.setBounds(430, 730, 70, 40);

        menos7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos7.setForeground(new java.awt.Color(34, 66, 73));
        menos7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos7MouseClicked(evt);
            }
        });
        getContentPane().add(menos7);
        menos7.setBounds(520, 740, 20, 20);

        val7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val7.setForeground(new java.awt.Color(34, 66, 73));
        val7.setText("0");
        val7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val7);
        val7.setBounds(550, 720, 40, 60);

        mas7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas7.setForeground(new java.awt.Color(34, 66, 73));
        mas7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas7MouseClicked(evt);
            }
        });
        getContentPane().add(mas7);
        mas7.setBounds(580, 740, 20, 20);

        comida2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        comida2.setForeground(new java.awt.Color(255, 102, 0));
        comida2.setText("LOMO GIUSEPPI VERDI");
        getContentPane().add(comida2);
        comida2.setBounds(60, 250, 250, 40);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(34, 66, 73));
        jLabel60.setText("6.");
        getContentPane().add(jLabel60);
        jLabel60.setBounds(30, 620, 50, 60);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(34, 66, 73));
        jLabel61.setText("7.");
        getContentPane().add(jLabel61);
        jLabel61.setBounds(30, 720, 50, 60);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(1, 30, 68));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Lomo acompañado de deliciosos fetuccinnis \nbañados en una clasica salsa italiana.");
        jTextArea3.setBorder(null);
        jTextArea3.setCaretColor(new java.awt.Color(1, 30, 68));
        jTextArea3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        jTextArea3.setEnabled(false);
        jTextArea3.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextArea3.setOpaque(false);
        jTextArea3.setPreferredSize(new java.awt.Dimension(280, 100));
        jTextArea3.setSelectionColor(new java.awt.Color(1, 30, 68));
        getContentPane().add(jTextArea3);
        jTextArea3.setBounds(60, 280, 320, 110);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Una version distinta pero igual de deliciosa \nacompañada con fetuccinnis en salsa hungara.");
        jTextArea4.setBorder(null);
        jTextArea4.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextArea4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        jTextArea4.setEnabled(false);
        jTextArea4.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextArea4.setPreferredSize(new java.awt.Dimension(280, 100));
        jTextArea4.setSelectionColor(new java.awt.Color(1, 30, 68));
        getContentPane().add(jTextArea4);
        jTextArea4.setBounds(60, 190, 310, 110);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(40, 870, 59, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/93b5f9913d2e4316cd6e541c67b9aed0.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 1880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos3MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val3.getText());
        if(i>0){
            i = i-1;

            val3.setText(String.valueOf(i));

        }
    }//GEN-LAST:event_menos3MouseClicked

    private void mas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas2MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val2.getText());
        if(i>=0 && i<=50){
            i = i+1;
            val2.setText(String.valueOf(i));

        }
    }//GEN-LAST:event_mas2MouseClicked

    private void menos4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos4MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val4.getText());
        if(i>0){
            i = i-1;
            val4.setText(String.valueOf(i));

        }
    }//GEN-LAST:event_menos4MouseClicked

    private void mas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas3MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val3.getText());
        if(i>=0 && i<=50){
            i = i+1;
            val3.setText(String.valueOf(i));

        }
    }//GEN-LAST:event_mas3MouseClicked

    private void menos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos2MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val2.getText());
        if(i>0){
            i = i-1;
            val2.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_menos2MouseClicked

    private void mas4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas4MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val4.getText());
        if(i>=0 && i<=50){
            i = i+1;
            val4.setText(String.valueOf(i));

        }
    }//GEN-LAST:event_mas4MouseClicked

    private void menos5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos5MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val5.getText());
        if(i>0){
            i = i-1;
            val5.setText(String.valueOf(i));

        }
    }//GEN-LAST:event_menos5MouseClicked

    private void mas5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas5MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val5.getText());
        if(i>=0 && i<=50){
            i = i+1;
            val5.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_mas5MouseClicked

    private void menos6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos6MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val6.getText());
        if(i>0){
            i = i-1;
            val6.setText(String.valueOf(i));

        }
    }//GEN-LAST:event_menos6MouseClicked

    private void mas6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas6MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val6.getText());
        if(i>=0 && i<=50){
            i = i+1;
            val6.setText(String.valueOf(i));

        }
    }//GEN-LAST:event_mas6MouseClicked

    private void menos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos1MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val1.getText());
        if(i>0){
            i = i-1;
            val1.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_menos1MouseClicked

    private void mas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas1MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val1.getText());
        if(i>=0 && i<=50){
            i = i+1;
            val1.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_mas1MouseClicked

    private void menos7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos7MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val7.getText());
        if(i>0){
            i = i-1;
            val7.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_menos7MouseClicked

    private void mas7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas7MouseClicked
        // TODO add your handling code here:
        int i = 0;
        i = Integer.parseInt(val7.getText());
        if(i>=0 && i<=50){
            i = i+1;
            val7.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_mas7MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuComida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comida1;
    private javax.swing.JLabel comida2;
    private javax.swing.JLabel comida3;
    private javax.swing.JLabel comida4;
    private javax.swing.JLabel comida5;
    private javax.swing.JLabel comida6;
    private javax.swing.JLabel comida7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mas1;
    private javax.swing.JLabel mas2;
    private javax.swing.JLabel mas3;
    private javax.swing.JLabel mas4;
    private javax.swing.JLabel mas5;
    private javax.swing.JLabel mas6;
    private javax.swing.JLabel mas7;
    private javax.swing.JLabel menos1;
    private javax.swing.JLabel menos2;
    private javax.swing.JLabel menos3;
    private javax.swing.JLabel menos4;
    private javax.swing.JLabel menos5;
    private javax.swing.JLabel menos6;
    private javax.swing.JLabel menos7;
    private javax.swing.JLabel precioComida1;
    private javax.swing.JLabel precioComida2;
    private javax.swing.JLabel precioComida3;
    private javax.swing.JLabel precioComida4;
    private javax.swing.JLabel precioComida5;
    private javax.swing.JLabel precioComida6;
    private javax.swing.JLabel precioComida7;
    private javax.swing.JLabel val1;
    private javax.swing.JLabel val2;
    private javax.swing.JLabel val3;
    private javax.swing.JLabel val4;
    private javax.swing.JLabel val5;
    private javax.swing.JLabel val6;
    private javax.swing.JLabel val7;
    // End of variables declaration//GEN-END:variables
}
