/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author reyna
 */
public class MenuPostres extends javax.swing.JFrame {
    Connection con = null;
    Statement stnt = null;
    String rut = Login.jTextField1.getText();
    /**
     * Creates new form MenuPostres
     */
    public MenuPostres() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        
    try {
    String url = "jdbc:mysql://localhost:3306/restaurante"; // direccion donde se encuentra la base de datos
    String usuario = "root"; // usuario de la gestion de base de datos
    String contraseña = "123"; // contraseña para entrar a la base de datos
                
    Class.forName("com.mysql.jdbc.Driver").newInstance(); // carga el driver para conectarce
    con = (Connection) DriverManager.getConnection(url,usuario,contraseña); // se conecta a la base de datos nuestro programa 
    if(con != null){
                System.out.println("Conexion Exitosa!");
            }else{
                System.out.println("Conexion Fallida!");                
            }
    }catch(Exception e){// excepciones en el caso de haber un error
         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null,e); 
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postre1 = new javax.swing.JLabel();
        postre2 = new javax.swing.JLabel();
        postre3 = new javax.swing.JLabel();
        postre4 = new javax.swing.JLabel();
        postre5 = new javax.swing.JLabel();
        postre6 = new javax.swing.JLabel();
        postre7 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        subPostre7 = new javax.swing.JTextArea();
        subPostre6 = new javax.swing.JTextArea();
        subPostre5 = new javax.swing.JTextArea();
        subPostre4 = new javax.swing.JTextArea();
        subPostre3 = new javax.swing.JTextArea();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        subPostre2 = new javax.swing.JTextArea();
        total2 = new javax.swing.JLabel();
        subPostre1 = new javax.swing.JTextArea();
        precioPostre3 = new javax.swing.JLabel();
        precioPostre2 = new javax.swing.JLabel();
        precioPostre5 = new javax.swing.JLabel();
        precioPostre6 = new javax.swing.JLabel();
        precioPostre1 = new javax.swing.JLabel();
        precioPostre7 = new javax.swing.JLabel();
        simbolo1 = new javax.swing.JLabel();
        simbolo2 = new javax.swing.JLabel();
        simbolo3 = new javax.swing.JLabel();
        simbolo4 = new javax.swing.JLabel();
        simbolo5 = new javax.swing.JLabel();
        simbolo6 = new javax.swing.JLabel();
        simbolo7 = new javax.swing.JLabel();
        simbolo8 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cantidad1 = new javax.swing.JTextField();
        cant1 = new javax.swing.JLabel();
        cant2 = new javax.swing.JLabel();
        cant3 = new javax.swing.JLabel();
        cantidad3 = new javax.swing.JTextField();
        cant4 = new javax.swing.JLabel();
        cantidad4 = new javax.swing.JTextField();
        cant5 = new javax.swing.JLabel();
        cantidad5 = new javax.swing.JTextField();
        cant6 = new javax.swing.JLabel();
        cantidad6 = new javax.swing.JTextField();
        cant7 = new javax.swing.JLabel();
        cantidad7 = new javax.swing.JTextField();
        cantidad2 = new javax.swing.JTextField();
        precioPostre4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(635, 930));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        postre1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        postre1.setForeground(new java.awt.Color(255, 102, 0));
        postre1.setText("MOUSSE DE CHOCOLATE");
        getContentPane().add(postre1);
        postre1.setBounds(60, 160, 250, 40);

        postre2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        postre2.setForeground(new java.awt.Color(255, 102, 0));
        postre2.setText("PASTEL OPERA");
        getContentPane().add(postre2);
        postre2.setBounds(60, 250, 250, 40);

        postre3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        postre3.setForeground(new java.awt.Color(255, 102, 0));
        postre3.setText("WAFFLES CON FRUTOS ROJOS");
        getContentPane().add(postre3);
        postre3.setBounds(60, 350, 310, 40);

        postre4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        postre4.setForeground(new java.awt.Color(255, 102, 0));
        postre4.setText("BIZCOCHO DE PISTACHO");
        getContentPane().add(postre4);
        postre4.setBounds(60, 440, 300, 40);

        postre5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        postre5.setForeground(new java.awt.Color(255, 102, 0));
        postre5.setText("BANANA SPLIT");
        getContentPane().add(postre5);
        postre5.setBounds(60, 540, 290, 40);

        postre6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        postre6.setForeground(new java.awt.Color(255, 102, 0));
        postre6.setText("MACEDONIA");
        getContentPane().add(postre6);
        postre6.setBounds(60, 630, 340, 40);

        postre7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        postre7.setForeground(new java.awt.Color(255, 102, 0));
        postre7.setText("COPA LIMON Y MENTA");
        getContentPane().add(postre7);
        postre7.setBounds(60, 730, 220, 40);

        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total.setForeground(new java.awt.Color(34, 66, 73));
        total.setText("TOTAL  $");
        getContentPane().add(total);
        total.setBounds(30, 860, 130, 40);

        total1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total1.setForeground(new java.awt.Color(34, 66, 73));
        getContentPane().add(total1);
        total1.setBounds(140, 860, 190, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 66, 73));
        jLabel4.setText("5.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 530, 60, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen5.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 40, 130, 90);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 66, 73));
        jLabel11.setText("1.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 150, 50, 60);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 66, 73));
        jLabel13.setText("2.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 240, 50, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(34, 66, 73));
        jLabel14.setText("3.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 340, 60, 60);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(34, 66, 73));
        jLabel15.setText("4.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 430, 50, 60);

        subPostre7.setEditable(false);
        subPostre7.setColumns(20);
        subPostre7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre7.setForeground(new java.awt.Color(34, 66, 73));
        subPostre7.setLineWrap(true);
        subPostre7.setRows(5);
        subPostre7.setText("Limon granizado, ron de caña y menta.");
        subPostre7.setBorder(null);
        subPostre7.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre7.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre7.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre7.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre7.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre7);
        subPostre7.setBounds(60, 760, 300, 110);

        subPostre6.setEditable(false);
        subPostre6.setColumns(20);
        subPostre6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre6.setForeground(new java.awt.Color(34, 66, 73));
        subPostre6.setLineWrap(true);
        subPostre6.setRows(5);
        subPostre6.setText("Helado de frambuesa, limon y frutilla \nsumergidas en frutas en almibar y nata.");
        subPostre6.setBorder(null);
        subPostre6.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre6.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre6.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre6.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre6.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre6);
        subPostre6.setBounds(60, 660, 300, 110);

        subPostre5.setEditable(false);
        subPostre5.setColumns(20);
        subPostre5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre5.setForeground(new java.awt.Color(34, 66, 73));
        subPostre5.setLineWrap(true);
        subPostre5.setRows(5);
        subPostre5.setText("Helado de fresa,chocolate, vainilla con nata montada en platanos naturales.");
        subPostre5.setBorder(null);
        subPostre5.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre5.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre5.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre5.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre5.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre5);
        subPostre5.setBounds(60, 570, 300, 110);

        subPostre4.setEditable(false);
        subPostre4.setColumns(20);
        subPostre4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre4.setForeground(new java.awt.Color(34, 66, 73));
        subPostre4.setLineWrap(true);
        subPostre4.setRows(5);
        subPostre4.setText("Esponjoso bizcocho de pistacho cubierto con\ncrema de chocolate blanco.");
        subPostre4.setBorder(null);
        subPostre4.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre4.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre4.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre4.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre4.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre4);
        subPostre4.setBounds(60, 470, 310, 110);

        subPostre3.setEditable(false);
        subPostre3.setColumns(20);
        subPostre3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre3.setForeground(new java.awt.Color(34, 66, 73));
        subPostre3.setLineWrap(true);
        subPostre3.setRows(5);
        subPostre3.setText("Waffles belgas con frutilla, mora y frambuesa decorados con crema batida y granillos de     chocolate.");
        subPostre3.setBorder(null);
        subPostre3.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre3.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre3.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre3.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre3.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre3);
        subPostre3.setBounds(60, 380, 310, 110);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(34, 66, 73));
        jLabel60.setText("6.");
        getContentPane().add(jLabel60);
        jLabel60.setBounds(30, 620, 50, 60);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(34, 66, 73));
        jLabel61.setText("7.");
        getContentPane().add(jLabel61);
        jLabel61.setBounds(30, 720, 50, 60);

        subPostre2.setEditable(false);
        subPostre2.setColumns(20);
        subPostre2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre2.setForeground(new java.awt.Color(34, 66, 73));
        subPostre2.setLineWrap(true);
        subPostre2.setRows(5);
        subPostre2.setText("Una base de biscuit, hojuelas crujientes y un mousse de chocolate amargo.");
        subPostre2.setBorder(null);
        subPostre2.setCaretColor(new java.awt.Color(34, 66, 73));
        subPostre2.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre2.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre2.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre2.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre2);
        subPostre2.setBounds(60, 280, 300, 110);

        total2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total2.setForeground(new java.awt.Color(34, 66, 73));
        total2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/agregar.png"))); // NOI18N
        total2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total2MouseClicked(evt);
            }
        });
        getContentPane().add(total2);
        total2.setBounds(400, 840, 200, 80);

        subPostre1.setEditable(false);
        subPostre1.setColumns(20);
        subPostre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subPostre1.setForeground(new java.awt.Color(34, 66, 73));
        subPostre1.setLineWrap(true);
        subPostre1.setRows(5);
        subPostre1.setText("Bizcocho de chocolate almendrado con \nmousse de chocolate sobre un espejo de\nBailey´s.");
        subPostre1.setBorder(null);
        subPostre1.setCaretColor(new java.awt.Color(255, 255, 255));
        subPostre1.setDisabledTextColor(new java.awt.Color(34, 66, 73));
        subPostre1.setMinimumSize(new java.awt.Dimension(150, 20));
        subPostre1.setPreferredSize(new java.awt.Dimension(280, 100));
        subPostre1.setSelectionColor(new java.awt.Color(34, 66, 73));
        getContentPane().add(subPostre1);
        subPostre1.setBounds(60, 190, 320, 110);

        precioPostre3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioPostre3.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre3.setText("3990");
        getContentPane().add(precioPostre3);
        precioPostre3.setBounds(440, 350, 70, 40);

        precioPostre2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioPostre2.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre2.setText("3990");
        getContentPane().add(precioPostre2);
        precioPostre2.setBounds(440, 250, 70, 40);

        precioPostre5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioPostre5.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre5.setText("4990");
        getContentPane().add(precioPostre5);
        precioPostre5.setBounds(440, 540, 70, 40);

        precioPostre6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioPostre6.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre6.setText("4990");
        getContentPane().add(precioPostre6);
        precioPostre6.setBounds(440, 630, 70, 40);

        precioPostre1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioPostre1.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre1.setText("3990");
        getContentPane().add(precioPostre1);
        precioPostre1.setBounds(440, 160, 70, 40);

        precioPostre7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioPostre7.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre7.setText("3990");
        getContentPane().add(precioPostre7);
        precioPostre7.setBounds(440, 730, 70, 40);

        simbolo1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo1.setForeground(new java.awt.Color(255, 102, 0));
        simbolo1.setText("$");
        getContentPane().add(simbolo1);
        simbolo1.setBounds(420, 250, 20, 40);

        simbolo2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo2.setForeground(new java.awt.Color(255, 102, 0));
        simbolo2.setText("$");
        getContentPane().add(simbolo2);
        simbolo2.setBounds(420, 350, 20, 40);

        simbolo3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo3.setForeground(new java.awt.Color(255, 102, 0));
        simbolo3.setText("$");
        getContentPane().add(simbolo3);
        simbolo3.setBounds(420, 440, 20, 40);

        simbolo4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo4.setForeground(new java.awt.Color(255, 102, 0));
        simbolo4.setText("$");
        getContentPane().add(simbolo4);
        simbolo4.setBounds(420, 540, 20, 40);

        simbolo5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo5.setForeground(new java.awt.Color(255, 102, 0));
        simbolo5.setText("$");
        getContentPane().add(simbolo5);
        simbolo5.setBounds(420, 630, 20, 40);

        simbolo6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo6.setForeground(new java.awt.Color(255, 102, 0));
        simbolo6.setText("$");
        getContentPane().add(simbolo6);
        simbolo6.setBounds(420, 730, 20, 40);

        simbolo7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo7.setForeground(new java.awt.Color(255, 102, 0));
        simbolo7.setText("$");
        getContentPane().add(simbolo7);
        simbolo7.setBounds(420, 160, 20, 40);

        simbolo8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        simbolo8.setForeground(new java.awt.Color(255, 102, 0));
        simbolo8.setText("$");
        getContentPane().add(simbolo8);
        simbolo8.setBounds(420, 160, 20, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("POSTRES");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 60, 230, 60);

        cantidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad1FocusLost(evt);
            }
        });
        cantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad1);
        cantidad1.setBounds(570, 170, 60, 30);

        cant1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant1.setForeground(new java.awt.Color(34, 66, 73));
        cant1.setText("Cant.");
        getContentPane().add(cant1);
        cant1.setBounds(510, 160, 70, 40);

        cant2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant2.setForeground(new java.awt.Color(34, 66, 73));
        cant2.setText("Cant.");
        getContentPane().add(cant2);
        cant2.setBounds(510, 250, 70, 40);

        cant3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant3.setForeground(new java.awt.Color(34, 66, 73));
        cant3.setText("Cant.");
        getContentPane().add(cant3);
        cant3.setBounds(510, 350, 70, 40);

        cantidad3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad3FocusLost(evt);
            }
        });
        cantidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad3ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad3);
        cantidad3.setBounds(570, 360, 60, 30);

        cant4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant4.setForeground(new java.awt.Color(34, 66, 73));
        cant4.setText("Cant.");
        getContentPane().add(cant4);
        cant4.setBounds(510, 440, 70, 40);

        cantidad4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad4FocusLost(evt);
            }
        });
        cantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad4ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad4);
        cantidad4.setBounds(570, 450, 60, 30);

        cant5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant5.setForeground(new java.awt.Color(34, 66, 73));
        cant5.setText("Cant.");
        getContentPane().add(cant5);
        cant5.setBounds(510, 540, 70, 40);

        cantidad5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad5FocusLost(evt);
            }
        });
        cantidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad5ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad5);
        cantidad5.setBounds(570, 550, 60, 30);

        cant6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant6.setForeground(new java.awt.Color(34, 66, 73));
        cant6.setText("Cant.");
        getContentPane().add(cant6);
        cant6.setBounds(510, 630, 70, 40);

        cantidad6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad6FocusLost(evt);
            }
        });
        cantidad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad6ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad6);
        cantidad6.setBounds(570, 640, 60, 30);

        cant7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cant7.setForeground(new java.awt.Color(34, 66, 73));
        cant7.setText("Cant.");
        getContentPane().add(cant7);
        cant7.setBounds(510, 730, 70, 40);

        cantidad7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad7FocusLost(evt);
            }
        });
        cantidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad7ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad7);
        cantidad7.setBounds(570, 740, 60, 30);

        cantidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad2FocusLost(evt);
            }
        });
        cantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad2ActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad2);
        cantidad2.setBounds(570, 260, 60, 30);

        precioPostre4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioPostre4.setForeground(new java.awt.Color(255, 102, 0));
        precioPostre4.setText("3990");
        getContentPane().add(precioPostre4);
        precioPostre4.setBounds(440, 440, 70, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/93b5f9913d2e4316cd6e541c67b9aed0.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 1880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void total2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total2MouseClicked
        // TODO add your handling code here:
        int precioTotal1 = (Integer.parseInt(precioPostre1.getText())*Integer.parseInt(cantidad1.getText()));
        int precioTotal2 = (Integer.parseInt(precioPostre2.getText())*Integer.parseInt(cantidad2.getText()));
        int precioTotal3 = (Integer.parseInt(precioPostre3.getText())*Integer.parseInt(cantidad3.getText()));
        int precioTotal4 = (Integer.parseInt(precioPostre4.getText())*Integer.parseInt(cantidad4.getText()));
        int precioTotal5 = (Integer.parseInt(precioPostre5.getText())*Integer.parseInt(cantidad5.getText()));
        int precioTotal6 = (Integer.parseInt(precioPostre6.getText())*Integer.parseInt(cantidad6.getText()));
        int precioTotal7 = (Integer.parseInt(precioPostre7.getText())*Integer.parseInt(cantidad7.getText()));

        
                try {
                stnt = con.createStatement();
                ResultSet rs = null;
                if(Integer.parseInt(cantidad1.getText())>=0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 17 && stock<"+cantidad1.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de "+ " " + rs.getInt("stock") + " en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),17,"
                                             +cantidad1.getText()+","+precioTotal1+")");}
                }if(Integer.parseInt(cantidad2.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 18 && stock<"+cantidad2.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de "+ " " + rs.getInt("stock") + " en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),18,"
                                             +cantidad2.getText()+","+precioTotal2+")");} 
                }if(Integer.parseInt(cantidad3.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 19 && stock<"+cantidad3.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de "+ " " + rs.getInt("stock") + " en " + rs.getString("nombre"),"Error",2);
                    }else{
                     rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),19,"
                                             +cantidad3.getText()+","+precioTotal3+")");}          
                }if(Integer.parseInt(cantidad4.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 20 && stock<"+cantidad4.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de "+ " " + rs.getInt("stock") + " en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),20,"
                                             +cantidad4.getText()+","+precioTotal4+")");}           
                }if(Integer.parseInt(cantidad5.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 21 && stock<"+cantidad5.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de "+ " " + rs.getInt("stock") + " en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),21,"
                                             +cantidad5.getText()+","+precioTotal5+")");}           
                }if(Integer.parseInt(cantidad6.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 22 && stock<"+cantidad6.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + " " + rs.getInt("stock") + " en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),22,"
                                             +cantidad6.getText()+","+precioTotal6+")");}           
                }if(Integer.parseInt(cantidad7.getText())>0){
                    rs = stnt.executeQuery("SELECT * FROM producto WHERE id = 23 && stock<"+cantidad7.getText()+"");               
                    if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Disculpe el inconveniente pero tenemos un stock de " + " " + rs.getInt("stock") + " en " + rs.getString("nombre"),"Error",2);
                    }else{
                    rs = stnt.executeQuery("CALL registroVen((SELECT MAX(factura.id) FROM usuario INNER JOIN factura ON factura.usuario_id_fk = usuario.id WHERE usuario.rut = '"+rut+"'),23,"
                                             +cantidad7.getText()+","+precioTotal7+")");}           
                }
                  }catch(Exception e){
                   }
        Carta go = new Carta();
        go.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_total2MouseClicked

    private void cantidad1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad1FocusGained
        // TODO add your handling code here:
        if(cantidad1.getText().equals("0")){
            cantidad1.setText("");

        }
    }//GEN-LAST:event_cantidad1FocusGained

    private void cantidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad1FocusLost
        // TODO add your handling code here:
        if(cantidad1.getText().equals("")){
            cantidad1.setText("0");
        }
    }//GEN-LAST:event_cantidad1FocusLost

    private void cantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad1ActionPerformed

    private void cantidad3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad3FocusGained
        // TODO add your handling code here:
        if(cantidad3.getText().equals("0")){
            cantidad3.setText("");}
    }//GEN-LAST:event_cantidad3FocusGained

    private void cantidad3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad3FocusLost
        // TODO add your handling code here:
        if(cantidad3.getText().equals("")){
            cantidad3.setText("0");
        }
    }//GEN-LAST:event_cantidad3FocusLost

    private void cantidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad3ActionPerformed

    private void cantidad4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad4FocusGained
        // TODO add your handling code here:
        if(cantidad4.getText().equals("0")){
            cantidad4.setText("");}
    }//GEN-LAST:event_cantidad4FocusGained

    private void cantidad4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad4FocusLost
        // TODO add your handling code here:
        if(cantidad4.getText().equals("")){
            cantidad4.setText("0");
        }
    }//GEN-LAST:event_cantidad4FocusLost

    private void cantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad4ActionPerformed

    private void cantidad5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad5FocusGained
        // TODO add your handling code here:
        if(cantidad5.getText().equals("0")){
            cantidad5.setText("");}
    }//GEN-LAST:event_cantidad5FocusGained

    private void cantidad5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad5FocusLost
        // TODO add your handling code here:
        if(cantidad5.getText().equals("")){
            cantidad5.setText("0");
        }
    }//GEN-LAST:event_cantidad5FocusLost

    private void cantidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad5ActionPerformed

    private void cantidad6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad6FocusGained
        // TODO add your handling code here:
        if(cantidad6.getText().equals("0")){
            cantidad6.setText("");
        }
    }//GEN-LAST:event_cantidad6FocusGained

    private void cantidad6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad6FocusLost
        // TODO add your handling code here:
        if(cantidad6.getText().equals("")){
            cantidad6.setText("0");}

    }//GEN-LAST:event_cantidad6FocusLost

    private void cantidad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad6ActionPerformed

    private void cantidad7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad7FocusGained
        // TODO add your handling code here:
        if(cantidad7.getText().equals("0")){
            cantidad7.setText("");}
    }//GEN-LAST:event_cantidad7FocusGained

    private void cantidad7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad7FocusLost
        // TODO add your handling code here:
        if(cantidad7.getText().equals("")){
            cantidad7.setText("0");
        }
    }//GEN-LAST:event_cantidad7FocusLost

    private void cantidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad7ActionPerformed

    private void cantidad2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad2FocusGained
        // TODO add your handling code here:
        if(cantidad2.getText().equals("0")){
            cantidad2.setText("");}
    }//GEN-LAST:event_cantidad2FocusGained

    private void cantidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad2FocusLost
        // TODO add your handling code here:
        if(cantidad2.getText().equals("")){
            cantidad2.setText("0");
        }
    }//GEN-LAST:event_cantidad2FocusLost

    private void cantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad2ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
                   if(cantidad1.getText().equals("")){
            cantidad1.setText("0");
            }if(cantidad2.getText().equals("")){
            cantidad2.setText("0");
            }if(cantidad3.getText().equals("")){
            cantidad3.setText("0");
            }if(cantidad4.getText().equals("")){
            cantidad4.setText("0");
            }if(cantidad5.getText().equals("")){
            cantidad5.setText("0");
            }if(cantidad6.getText().equals("")){
            cantidad6.setText("0");
            }if(cantidad7.getText().equals("")){
            cantidad7.setText("0");}     
       if(Integer.parseInt(cantidad1.getText())>=0){    
       int a = Integer.parseInt(precioPostre1.getText());
       int b = Integer.parseInt(precioPostre2.getText());
       int c = Integer.parseInt(precioPostre3.getText());
       int d = Integer.parseInt(precioPostre4.getText());
       int e = Integer.parseInt(precioPostre5.getText());
       int f = Integer.parseInt(precioPostre6.getText());
       int g = Integer.parseInt(precioPostre7.getText());
       int aa = Integer.parseInt(cantidad1.getText());
       int bb = Integer.parseInt(cantidad2.getText());
       int cc = Integer.parseInt(cantidad3.getText());
       int dd = Integer.parseInt(cantidad4.getText());
       int ee = Integer.parseInt(cantidad5.getText());
       int ff = Integer.parseInt(cantidad6.getText());
       int gg = Integer.parseInt(cantidad7.getText());
       total1.setText(String.valueOf((a*aa)+(b*bb)+(c*cc)+(d*dd)+(e*ee)+(f*ff)+(g*gg)));
       }
    }//GEN-LAST:event_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPostres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cant1;
    private javax.swing.JLabel cant2;
    private javax.swing.JLabel cant3;
    private javax.swing.JLabel cant4;
    private javax.swing.JLabel cant5;
    private javax.swing.JLabel cant6;
    private javax.swing.JLabel cant7;
    private javax.swing.JTextField cantidad1;
    private javax.swing.JTextField cantidad2;
    private javax.swing.JTextField cantidad3;
    private javax.swing.JTextField cantidad4;
    private javax.swing.JTextField cantidad5;
    private javax.swing.JTextField cantidad6;
    private javax.swing.JTextField cantidad7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel postre1;
    private javax.swing.JLabel postre2;
    private javax.swing.JLabel postre3;
    private javax.swing.JLabel postre4;
    private javax.swing.JLabel postre5;
    private javax.swing.JLabel postre6;
    private javax.swing.JLabel postre7;
    private javax.swing.JLabel precioPostre1;
    private javax.swing.JLabel precioPostre2;
    private javax.swing.JLabel precioPostre3;
    private javax.swing.JLabel precioPostre4;
    private javax.swing.JLabel precioPostre5;
    private javax.swing.JLabel precioPostre6;
    private javax.swing.JLabel precioPostre7;
    private javax.swing.JLabel simbolo1;
    private javax.swing.JLabel simbolo2;
    private javax.swing.JLabel simbolo3;
    private javax.swing.JLabel simbolo4;
    private javax.swing.JLabel simbolo5;
    private javax.swing.JLabel simbolo6;
    private javax.swing.JLabel simbolo7;
    private javax.swing.JLabel simbolo8;
    private javax.swing.JTextArea subPostre1;
    private javax.swing.JTextArea subPostre2;
    private javax.swing.JTextArea subPostre3;
    private javax.swing.JTextArea subPostre4;
    private javax.swing.JTextArea subPostre5;
    private javax.swing.JTextArea subPostre6;
    private javax.swing.JTextArea subPostre7;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    // End of variables declaration//GEN-END:variables
}
