/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

/**
 *
 * @author reyna
 */
public class MenuBebidas extends javax.swing.JFrame {

        

    /**
     * Creates new form MenuBebidas
     */
    public MenuBebidas() {
        initComponents(); 
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menos3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        val3 = new javax.swing.JLabel();
        mas2 = new javax.swing.JLabel();
        precioBebida3 = new javax.swing.JLabel();
        bebida3 = new javax.swing.JLabel();
        bebida4 = new javax.swing.JLabel();
        precioBebida4 = new javax.swing.JLabel();
        menos4 = new javax.swing.JLabel();
        val4 = new javax.swing.JLabel();
        mas3 = new javax.swing.JLabel();
        bebida2 = new javax.swing.JLabel();
        precioBebida2 = new javax.swing.JLabel();
        menos2 = new javax.swing.JLabel();
        val2 = new javax.swing.JLabel();
        mas4 = new javax.swing.JLabel();
        bebida5 = new javax.swing.JLabel();
        precioBebida5 = new javax.swing.JLabel();
        menos5 = new javax.swing.JLabel();
        val5 = new javax.swing.JLabel();
        mas5 = new javax.swing.JLabel();
        bebida6 = new javax.swing.JLabel();
        precioBebida6 = new javax.swing.JLabel();
        menos6 = new javax.swing.JLabel();
        val6 = new javax.swing.JLabel();
        mas6 = new javax.swing.JLabel();
        bebida8 = new javax.swing.JLabel();
        precioBebida8 = new javax.swing.JLabel();
        menos8 = new javax.swing.JLabel();
        val8 = new javax.swing.JLabel();
        mas8 = new javax.swing.JLabel();
        bebida9 = new javax.swing.JLabel();
        precioBebida9 = new javax.swing.JLabel();
        menos9 = new javax.swing.JLabel();
        val9 = new javax.swing.JLabel();
        mas9 = new javax.swing.JLabel();
        bebida1 = new javax.swing.JLabel();
        precioBebida1 = new javax.swing.JLabel();
        menos1 = new javax.swing.JLabel();
        val1 = new javax.swing.JLabel();
        mas1 = new javax.swing.JLabel();
        bebida7 = new javax.swing.JLabel();
        precioBebida7 = new javax.swing.JLabel();
        menos7 = new javax.swing.JLabel();
        val7 = new javax.swing.JLabel();
        mas7 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 770));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 66, 73));
        jLabel4.setText("5.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 430, 60, 60);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 66, 73));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen4.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 20, 40, 100);

        menos3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos3.setForeground(new java.awt.Color(34, 66, 73));
        menos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos3MouseClicked(evt);
            }
        });
        getContentPane().add(menos3);
        menos3.setBounds(400, 350, 20, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(34, 66, 73));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen4.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 10, 40, 110);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(34, 66, 73));
        jLabel7.setText("BEBIDAS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 50, 230, 60);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 66, 73));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen4.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 20, 50, 120);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 66, 73));
        jLabel11.setText("1.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 230, 50, 60);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 66, 73));
        jLabel13.setText("2.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 280, 50, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(34, 66, 73));
        jLabel14.setText("3.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 330, 60, 60);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(34, 66, 73));
        jLabel15.setText("4.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 380, 50, 60);

        val3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val3.setForeground(new java.awt.Color(34, 66, 73));
        val3.setText("0");
        val3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val3);
        val3.setBounds(430, 330, 40, 50);

        mas2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas2.setForeground(new java.awt.Color(34, 66, 73));
        mas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas2MouseClicked(evt);
            }
        });
        getContentPane().add(mas2);
        mas2.setBounds(470, 300, 20, 20);

        precioBebida3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida3.setForeground(new java.awt.Color(34, 66, 73));
        precioBebida3.setText("$1500");
        getContentPane().add(precioBebida3);
        precioBebida3.setBounds(310, 340, 70, 40);

        bebida3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida3.setForeground(new java.awt.Color(34, 66, 73));
        bebida3.setText("Fanta (500 ml)");
        getContentPane().add(bebida3);
        bebida3.setBounds(50, 330, 160, 60);

        bebida4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida4.setForeground(new java.awt.Color(34, 66, 73));
        bebida4.setText("Fanta Zero (500 ml)");
        getContentPane().add(bebida4);
        bebida4.setBounds(50, 380, 200, 60);

        precioBebida4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida4.setForeground(new java.awt.Color(34, 66, 73));
        precioBebida4.setText("$1500");
        getContentPane().add(precioBebida4);
        precioBebida4.setBounds(310, 390, 70, 40);

        menos4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos4.setForeground(new java.awt.Color(34, 66, 73));
        menos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos4MouseClicked(evt);
            }
        });
        getContentPane().add(menos4);
        menos4.setBounds(400, 400, 20, 20);

        val4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val4.setForeground(new java.awt.Color(34, 66, 73));
        val4.setText("0");
        val4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val4);
        val4.setBounds(430, 380, 40, 50);

        mas3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas3.setForeground(new java.awt.Color(34, 66, 73));
        mas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas3MouseClicked(evt);
            }
        });
        getContentPane().add(mas3);
        mas3.setBounds(470, 350, 20, 20);

        bebida2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida2.setForeground(new java.awt.Color(34, 66, 73));
        bebida2.setText("Coca-Cola Zero (500 ml)");
        getContentPane().add(bebida2);
        bebida2.setBounds(50, 280, 250, 60);

        precioBebida2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida2.setForeground(new java.awt.Color(34, 66, 73));
        precioBebida2.setText("$1500");
        getContentPane().add(precioBebida2);
        precioBebida2.setBounds(310, 290, 70, 40);

        menos2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos2.setForeground(new java.awt.Color(34, 66, 73));
        menos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos2MouseClicked(evt);
            }
        });
        getContentPane().add(menos2);
        menos2.setBounds(400, 300, 20, 20);

        val2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val2.setForeground(new java.awt.Color(34, 66, 73));
        val2.setText("0");
        val2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val2);
        val2.setBounds(430, 280, 40, 50);

        mas4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas4.setForeground(new java.awt.Color(34, 66, 73));
        mas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas4MouseClicked(evt);
            }
        });
        getContentPane().add(mas4);
        mas4.setBounds(470, 400, 20, 20);

        bebida5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida5.setForeground(new java.awt.Color(34, 66, 73));
        bebida5.setText("Sprite (500 ml)");
        getContentPane().add(bebida5);
        bebida5.setBounds(50, 430, 180, 60);

        precioBebida5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida5.setForeground(new java.awt.Color(34, 66, 73));
        precioBebida5.setText("$1500");
        getContentPane().add(precioBebida5);
        precioBebida5.setBounds(310, 440, 70, 40);

        menos5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos5.setForeground(new java.awt.Color(34, 66, 73));
        menos5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos5MouseClicked(evt);
            }
        });
        getContentPane().add(menos5);
        menos5.setBounds(400, 450, 20, 20);

        val5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val5.setForeground(new java.awt.Color(34, 66, 73));
        val5.setText("0");
        val5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val5);
        val5.setBounds(430, 430, 40, 50);

        mas5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas5.setForeground(new java.awt.Color(34, 66, 73));
        mas5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas5MouseClicked(evt);
            }
        });
        getContentPane().add(mas5);
        mas5.setBounds(470, 450, 20, 20);

        bebida6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida6.setForeground(new java.awt.Color(34, 66, 73));
        bebida6.setText("Sprite Zero (500 ml)");
        getContentPane().add(bebida6);
        bebida6.setBounds(50, 480, 200, 60);

        precioBebida6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida6.setForeground(new java.awt.Color(34, 66, 73));
        precioBebida6.setText("$1500");
        getContentPane().add(precioBebida6);
        precioBebida6.setBounds(310, 490, 70, 40);

        menos6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos6.setForeground(new java.awt.Color(34, 66, 73));
        menos6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos6MouseClicked(evt);
            }
        });
        getContentPane().add(menos6);
        menos6.setBounds(400, 500, 20, 20);

        val6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val6.setForeground(new java.awt.Color(34, 66, 73));
        val6.setText("0");
        val6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val6);
        val6.setBounds(430, 480, 40, 50);

        mas6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas6.setForeground(new java.awt.Color(34, 66, 73));
        mas6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas6MouseClicked(evt);
            }
        });
        getContentPane().add(mas6);
        mas6.setBounds(470, 500, 20, 20);

        bebida8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida8.setForeground(new java.awt.Color(34, 66, 73));
        bebida8.setText("Jugo natural melon");
        getContentPane().add(bebida8);
        bebida8.setBounds(50, 580, 260, 60);

        precioBebida8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida8.setForeground(new java.awt.Color(34, 66, 73));
        precioBebida8.setText("$2000");
        getContentPane().add(precioBebida8);
        precioBebida8.setBounds(310, 590, 70, 40);

        menos8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos8.setForeground(new java.awt.Color(34, 66, 73));
        menos8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos8MouseClicked(evt);
            }
        });
        getContentPane().add(menos8);
        menos8.setBounds(400, 600, 20, 20);

        val8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val8.setForeground(new java.awt.Color(34, 66, 73));
        val8.setText("0");
        val8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val8);
        val8.setBounds(430, 580, 40, 50);

        mas8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas8.setForeground(new java.awt.Color(34, 66, 73));
        mas8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas8MouseClicked(evt);
            }
        });
        getContentPane().add(mas8);
        mas8.setBounds(470, 600, 20, 20);

        bebida9.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida9.setForeground(new java.awt.Color(34, 66, 73));
        bebida9.setText("Jugo natural piña");
        getContentPane().add(bebida9);
        bebida9.setBounds(50, 630, 280, 60);

        precioBebida9.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida9.setForeground(new java.awt.Color(34, 66, 73));
        precioBebida9.setText("$2000");
        getContentPane().add(precioBebida9);
        precioBebida9.setBounds(310, 640, 70, 40);

        menos9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos9.setForeground(new java.awt.Color(34, 66, 73));
        menos9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos9MouseClicked(evt);
            }
        });
        getContentPane().add(menos9);
        menos9.setBounds(400, 650, 20, 20);

        val9.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val9.setForeground(new java.awt.Color(34, 66, 73));
        val9.setText("0");
        val9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val9);
        val9.setBounds(430, 630, 40, 50);

        mas9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas9.setForeground(new java.awt.Color(34, 66, 73));
        mas9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas9MouseClicked(evt);
            }
        });
        getContentPane().add(mas9);
        mas9.setBounds(470, 650, 20, 20);

        bebida1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida1.setForeground(new java.awt.Color(34, 66, 73));
        bebida1.setText("Coca-Cola (500 ml)");
        getContentPane().add(bebida1);
        bebida1.setBounds(50, 230, 220, 60);

        precioBebida1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida1.setForeground(new java.awt.Color(34, 66, 73));
        precioBebida1.setText("$1500");
        getContentPane().add(precioBebida1);
        precioBebida1.setBounds(310, 240, 70, 40);

        menos1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos1.setForeground(new java.awt.Color(34, 66, 73));
        menos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos1MouseClicked(evt);
            }
        });
        getContentPane().add(menos1);
        menos1.setBounds(400, 250, 20, 20);

        val1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val1.setForeground(new java.awt.Color(34, 66, 73));
        val1.setText("0");
        val1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val1);
        val1.setBounds(430, 230, 40, 50);

        mas1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas1.setForeground(new java.awt.Color(34, 66, 73));
        mas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas1MouseClicked(evt);
            }
        });
        getContentPane().add(mas1);
        mas1.setBounds(470, 250, 20, 20);

        bebida7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        bebida7.setForeground(new java.awt.Color(34, 66, 73));
        bebida7.setText("Jugo natural frambuesa");
        getContentPane().add(bebida7);
        bebida7.setBounds(50, 530, 240, 60);

        precioBebida7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        precioBebida7.setForeground(new java.awt.Color(34, 66, 73));
        precioBebida7.setText("$2000");
        getContentPane().add(precioBebida7);
        precioBebida7.setBounds(310, 540, 70, 40);

        menos7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menos7.setForeground(new java.awt.Color(34, 66, 73));
        menos7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/-.png"))); // NOI18N
        menos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos7MouseClicked(evt);
            }
        });
        getContentPane().add(menos7);
        menos7.setBounds(400, 550, 20, 20);

        val7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        val7.setForeground(new java.awt.Color(34, 66, 73));
        val7.setText("0");
        val7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(val7);
        val7.setBounds(430, 530, 40, 50);

        mas7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mas7.setForeground(new java.awt.Color(34, 66, 73));
        mas7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen7.png"))); // NOI18N
        mas7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas7MouseClicked(evt);
            }
        });
        getContentPane().add(mas7);
        mas7.setBounds(470, 550, 20, 20);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(34, 66, 73));
        jLabel60.setText("6.");
        getContentPane().add(jLabel60);
        jLabel60.setBounds(20, 480, 50, 60);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(34, 66, 73));
        jLabel61.setText("7.");
        getContentPane().add(jLabel61);
        jLabel61.setBounds(20, 530, 50, 60);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(34, 66, 73));
        jLabel62.setText("8.");
        getContentPane().add(jLabel62);
        jLabel62.setBounds(20, 580, 60, 60);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(34, 66, 73));
        jLabel63.setText("9.");
        getContentPane().add(jLabel63);
        jLabel63.setBounds(20, 630, 50, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/93b5f9913d2e4316cd6e541c67b9aed0.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 570, 1880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos3MouseClicked
        // TODO add your handling code here:   
        int i = 0;
        i = Integer.parseInt(val3.getText());
        if(i>0){
            i = i-1;
            
            val3.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_menos3MouseClicked

    private void mas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas2MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val2.getText());
            if(i>=0 && i<=50){
            i = i+1;
            val2.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_mas2MouseClicked

    private void menos4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos4MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val4.getText());
            if(i>0){
            i = i-1;
            val4.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_menos4MouseClicked

    private void mas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas3MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val3.getText());
            if(i>=0 && i<=50){
            i = i+1;
            val3.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_mas3MouseClicked

    private void menos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos2MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val2.getText());
            if(i>0){
            i = i-1;
            val2.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_menos2MouseClicked

    private void mas4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas4MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val4.getText());
            if(i>=0 && i<=50){
            i = i+1;
            val4.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_mas4MouseClicked

    private void menos5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos5MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val5.getText());
            if(i>0){
            i = i-1;
            val5.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_menos5MouseClicked

    private void mas5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas5MouseClicked
        // TODO add your handling code here:  
            int i = 0;
            i = Integer.parseInt(val5.getText());
            if(i>=0 && i<=50){
            i = i+1;
            val5.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_mas5MouseClicked

    private void menos6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos6MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val6.getText());
            if(i>0){
            i = i-1;
            val6.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_menos6MouseClicked

    private void mas6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas6MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val6.getText());
            if(i>=0 && i<=50){
            i = i+1;
            val6.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_mas6MouseClicked

    private void menos8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos8MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val8.getText());
            if(i>0){
            i = i-1;
            val8.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_menos8MouseClicked

    private void mas8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas8MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val8.getText());
            if(i>=0 && i<=50){
            i = i+1;
            val8.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_mas8MouseClicked

    private void menos9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos9MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val9.getText());
            if(i>0){
            i = i-1;
            val9.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_menos9MouseClicked

    private void mas9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas9MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val9.getText());
            if(i>=0 && i<=50){
            i = i+1;
            val9.setText(String.valueOf(i));
    
        }
    }//GEN-LAST:event_mas9MouseClicked

    private void menos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos1MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val1.getText());
            if(i>0){
            i = i-1;
            val1.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_menos1MouseClicked

    private void mas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas1MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val1.getText());
            if(i>=0 && i<=50){
            i = i+1;
            val1.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_mas1MouseClicked

    private void menos7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos7MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val7.getText());
            if(i>0){
            i = i-1;
            val7.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_menos7MouseClicked

    private void mas7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas7MouseClicked
        // TODO add your handling code here:
            int i = 0;
            i = Integer.parseInt(val7.getText());
            if(i>=0 && i<=50){
            i = i+1;
            val7.setText(String.valueOf(i));
          }
    }//GEN-LAST:event_mas7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bebida1;
    private javax.swing.JLabel bebida2;
    private javax.swing.JLabel bebida3;
    private javax.swing.JLabel bebida4;
    private javax.swing.JLabel bebida5;
    private javax.swing.JLabel bebida6;
    private javax.swing.JLabel bebida7;
    private javax.swing.JLabel bebida8;
    private javax.swing.JLabel bebida9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mas1;
    private javax.swing.JLabel mas2;
    private javax.swing.JLabel mas3;
    private javax.swing.JLabel mas4;
    private javax.swing.JLabel mas5;
    private javax.swing.JLabel mas6;
    private javax.swing.JLabel mas7;
    private javax.swing.JLabel mas8;
    private javax.swing.JLabel mas9;
    private javax.swing.JLabel menos1;
    private javax.swing.JLabel menos2;
    private javax.swing.JLabel menos3;
    private javax.swing.JLabel menos4;
    private javax.swing.JLabel menos5;
    private javax.swing.JLabel menos6;
    private javax.swing.JLabel menos7;
    private javax.swing.JLabel menos8;
    private javax.swing.JLabel menos9;
    private javax.swing.JLabel precioBebida1;
    private javax.swing.JLabel precioBebida2;
    private javax.swing.JLabel precioBebida3;
    private javax.swing.JLabel precioBebida4;
    private javax.swing.JLabel precioBebida5;
    private javax.swing.JLabel precioBebida6;
    private javax.swing.JLabel precioBebida7;
    private javax.swing.JLabel precioBebida8;
    private javax.swing.JLabel precioBebida9;
    private javax.swing.JLabel val1;
    private javax.swing.JLabel val2;
    private javax.swing.JLabel val3;
    private javax.swing.JLabel val4;
    private javax.swing.JLabel val5;
    private javax.swing.JLabel val6;
    private javax.swing.JLabel val7;
    private javax.swing.JLabel val8;
    private javax.swing.JLabel val9;
    // End of variables declaration//GEN-END:variables
}
